In [28]:
num_nodes=7
edge_types=2
a = torch.zeros((1, 1, num_nodes*(num_nodes-2), edge_types), requires_grad=True, device="cuda")
b = torch.zeros((1, 1, 1, edge_types), requires_grad=False, device="cuda")
b[:,:,:,0]=1
c = torch.zeros((1, 1, num_nodes-1, edge_types), requires_grad=True, device="cuda")
d=torch.zeros((1, 1, num_nodes, edge_types), requires_grad=True, device="cuda")


TypeError: cat() received an invalid combination of arguments - got (Tensor, Tensor, dim=int), but expected one of:
 * (tuple of Tensors tensors, name dim, Tensor out)
      didn't match because some of the keywords were incorrect: dim
 * (tuple of Tensors tensors, int dim, Tensor out)
      didn't match because some of the keywords were incorrect: dim


In [61]:
x = np.load('data/feat_valid_causal_vel.npy')
x.shape
new_time=np.zeros((1,19,9))
new_time[:,:,0]=np.linspace(0,36,19)
new_time[:,:,-1]=1
time=np.tile(np.expand_dims(new_time, 0),(x.shape[0],1,1,1))
time.shape
final=np.zeros((x.shape[0], x.shape[1]+1, x.shape[2], x.shape[3]+1))
final[:,:-1,:,:-1]=x
final[:,-1:,:,:]=time
np.save('data/feat_valid_causal_vel_time.npy', final)

(60000, 7, 19, 8)

In [ ]:
#[num_sims, num_atoms, num_timesteps, num_dims] 5x5x5x5,5,4,1
step=19
interval=2
data=[]
for shape in [1,2,3]:
    s=[[shape,1,0,0,0,0,0,0]]*step
    for color in :
        print(shape,color)
        c=[[color,0,1,0,0,0,0,0]]*step
        for mu in mus:
            friction = [[mu,0,0,1,0,0,0,0]]*step
            for theta in thetas:
                t = [[theta,0,0,0,1,0,0,0]]*step
                for mass in masses:
                    m = [[mass,0,0,0,0,1,0,0]]*step
                    for u0 in u0s:
#                         u = [u0]*step
                        for v0 in v0s:
#                             v = [v0]*step
                            loc = np.zeros((step, 8))
                            loc[0,0] = u0
                            loc[:,1:] =[0,0,0,0,0,0,1]
                            vel = np.zeros((step, 8))
                            vel[0,0] = v0
                            vel[:,1:] =[0,0,0,0,0,1,0]
                            for i in range(1, step):
                                loc[i, 0]=loc[i-1, 0]+vel[i-1,0]*interval+0.5*g*(np.sin(theta)-np.cos(theta)*mu)*(interval**2)
                                vel[i, 0] = vel[i-1, 0]+g*(np.sin(theta)-np.cos(theta)*mu)
                            #monitor the loss of vel_curr,loc_curr, 
                            #each dim 1+one_hot_semantic=9
                            #self.rel_graph=8x8
                            #
                            #[s,c,friction,t,m,vel_curr,loc_curr], [s,c,friction,t,m, [loc_prevs]]
                            trial=np.stack([s,c,friction,t,m,vel,loc],axis=0) 
                            data.append(trial)
                            
                          
                            

                    

1 40
1 57
1 213
1 9
1 254


In [87]:
#[num_sims, num_atoms, num_timesteps, num_dims] 5x5x5x5,5,4,1
step=19
interval=2
data=[]
for shape in [1,2,3]:
    s=[shape]*step
    for color in [40,57,213,9,254]:
        c=[color]*step
        for mu in mus:
            friction = [mu]*step
            for theta in thetas:
                t = [theta]*step
                for mass in masses:
                    m = [mass]*step
                    for u0 in u0s:
#                         u = [u0]*step
                        for v0 in v0s:
#                             v = [v0]*step
                            loc = np.zeros(step)
                            loc[0] = u0
#                             loc[:,1:] =[0,0,0,0,0,0,1]
                            vel = np.zeros(step)
                            vel[0] = v0
#                             vel[:,1:] =[0,0,0,0,0,1,0]
                            for i in range(1, step):
                                loc[i]=loc[i-1]+vel[i-1]*interval+0.5*g*(np.sin(theta)-np.cos(theta)*mu)*(interval**2)
                                vel[i] = vel[i-1]+g*(np.sin(theta)-np.cos(theta)*mu)
                            #monitor the loss of vel_curr,loc_curr, 
                            #each dim 1+one_hot_semantic=9
                            #self.rel_graph=8x8
                            #
                            #[s,c,friction,t,m,vel_curr,loc_curr], [s,c,friction,t,m, [loc_prevs]]
                            trial=np.stack([s,c,friction,t,m,vel,loc],axis=0) 
                            data.append(trial)

In [277]:
# new_data=np.expand_dims(np.array(data),-1)
data_new=np.array(data)
# new_data.shape
# data_new=new_data
data_new.shape

(67500, 7, 19, 8)

In [97]:
data_new[0,:,2,:]

array([[1.00000000e+00],
       [4.00000000e+01],
       [1.00000000e-03],
       [3.49065850e-02],
       [5.00000000e-01],
       [6.64442075e-01],
       [2.09332623e+00]])

In [7]:
# edge=np.array([[0,0,0,0,0,0,0,0],\
#                [0,0,0,0,0,0,0,0],\
#                [0,0,0,0,0,0,0,1],\
#                [0,0,0,0,0,0,0,1],\
#                [0,0,0,0,0,0,0,0],\
#                [0,0,0,0,0,0,0,1],\
#                [0,0,0,0,0,0,0,1],\
#                [0,0,0,0,0,0,0,0]])  
# edge=np.array([[0,0,0,0,0,0,0],\
#                [0,0,0,0,0,0,0],\
#                [0,0,0,0,0,0,1],\
#                [0,0,0,0,0,0,1],\
#                [0,0,0,0,0,0,0],\
#                [0,0,0,0,0,0,1],\
#                [0,0,0,0,0,0,0]]) 
edge=np.repeat(np.expand_dims(edge,0),data_new_1.shape[0],axis=0)
edge.shape

(600000, 9, 9)

In [6]:
data_new_1=data_new[:600000]
arr=np.arange(data_new_1.shape[0])
np.random.shuffle(arr)
print(arr[:10])
start_1 = int(data_new_1.shape[0]*0.75)
start_2 = int(data_new_1.shape[0]*0.85)
np.save('data/feat_train_causal_vel_sincos.npy',data_new_1[arr[:start_1]])
np.save('data/feat_valid_causal_vel_sincos.npy',data_new_1[arr[start_1:start_2]])
np.save('data/feat_test_causal_vel_sincos.npy',data_new_1[arr[start_2:]])

[  9323 102535 350601  22294 372254 527304  49301  31565 175517 497442]


In [8]:
start_1 = int(600000*0.75)
start_2 = int(600000*0.85)
np.save('data/edges_train_causal_vel_sincos.npy',edge[:start_1])
np.save('data/edges_valid_causal_vel_sincos.npy',edge[start_1:start_2])
np.save('data/edges_test_causal_vel_sincos.npy',edge[start_2:])

In [69]:
new_data = np.zeros_like(data)
for i in range(0, data.shape[1]):
        new_data[:,i,:,:] = (data[:,i,:,:] - np.min(data[:,i,:,:]))*2/(np.max(data[:,i,:,:])-np.min(data[:,i,:,:]))-1

In [74]:
np.max(new_data[:,2,:,:])

1.0

In [16]:
debug = np.squeeze(np.load('logs/exp2020-06-27T06:41:05.204948/100_rel_graph_grad.npy'))

In [18]:
 debug.shape

(352, 56, 2)

In [35]:
import torch.nn as nn
import torch.nn.functional as F
import torch
F.softmax(torch.Tensor(np.squeeze(np.load('../NRI/logs/exp2020-06-27T06:41:05.204948/0_rel_graph.npy'))[0]),dim=1)

tensor([[0.4561, 0.5439],
        [0.4784, 0.5216],
        [0.4419, 0.5581],
        [0.5065, 0.4935],
        [0.5450, 0.4550],
        [0.4704, 0.5296],
        [0.4956, 0.5044],
        [0.4326, 0.5674],
        [0.4694, 0.5306],
        [0.5221, 0.4779],
        [0.5498, 0.4502],
        [0.4617, 0.5383],
        [0.5222, 0.4778],
        [0.5739, 0.4261],
        [0.5347, 0.4653],
        [0.4973, 0.5027],
        [0.4888, 0.5112],
        [0.5077, 0.4923],
        [0.4504, 0.5496],
        [0.5579, 0.4421],
        [0.5229, 0.4771],
        [0.5078, 0.4922],
        [0.5242, 0.4758],
        [0.4749, 0.5251],
        [0.5070, 0.4930],
        [0.4725, 0.5275],
        [0.5110, 0.4890],
        [0.5580, 0.4420],
        [0.5095, 0.4905],
        [0.5257, 0.4743],
        [0.5509, 0.4491],
        [0.5185, 0.4815],
        [0.5544, 0.4456],
        [0.5458, 0.4542],
        [0.4814, 0.5186],
        [0.4988, 0.5012],
        [0.4573, 0.5427],
        [0.4657, 0.5343],
        [0.4

In [34]:
F.softmax(torch.Tensor(np.squeeze(np.load('logs/exp2020-06-27T06:41:05.204948/10_rel_graph.npy'))[0]),dim=1)

tensor([[0.7000, 0.3000],
        [0.7000, 0.3000],
        [0.7000, 0.3000],
        [0.7000, 0.3000],
        [0.7000, 0.3000],
        [0.7000, 0.3000],
        [0.7000, 0.3000],
        [0.7000, 0.3000],
        [0.7000, 0.3000],
        [0.7000, 0.3000],
        [0.7000, 0.3000],
        [0.7000, 0.3000],
        [0.7000, 0.3000],
        [0.7000, 0.3000],
        [0.7000, 0.3000],
        [0.7000, 0.3000],
        [0.7000, 0.3000],
        [0.7000, 0.3000],
        [0.7000, 0.3000],
        [0.7000, 0.3000],
        [0.7000, 0.3000],
        [0.7000, 0.3000],
        [0.7000, 0.3000],
        [0.7000, 0.3000],
        [0.7000, 0.3000],
        [0.7000, 0.3000],
        [0.7000, 0.3000],
        [0.7000, 0.3000],
        [0.7000, 0.3000],
        [0.7000, 0.3000],
        [0.7000, 0.3000],
        [0.7000, 0.3000],
        [0.7000, 0.3000],
        [0.7000, 0.3000],
        [0.7000, 0.3000],
        [0.7000, 0.3000],
        [0.7000, 0.3000],
        [0.7000, 0.3000],
        [0.7

In [98]:
#gt: 20,27,41,48
torch.nonzero(F.softmax(torch.Tensor(np.squeeze(np.load('../NRI/logs/exp2020-06-27T19:11:06.878733/20_rel_graph.npy'))[0]),dim=1).argmax(1))


tensor([[ 6],
        [ 7],
        [20],
        [49],
        [50],
        [51],
        [52],
        [53],
        [54],
        [55]])

In [85]:
F.softmax(torch.Tensor(np.squeeze(np.load('../NRI/logs/exp2020-06-27T18:33:05.207373/150_rel_graph.npy'))[0]),dim=1)


tensor([[0.7402, 0.2598],
        [0.7477, 0.2523],
        [0.7370, 0.2630],
        [0.7531, 0.2469],
        [0.7642, 0.2358],
        [0.7428, 0.2572],
        [0.7183, 0.2817],
        [0.6943, 0.3057],
        [0.7546, 0.2454],
        [0.7804, 0.2196],
        [0.7771, 0.2229],
        [0.7500, 0.2500],
        [0.7788, 0.2212],
        [0.7915, 0.2085],
        [0.7376, 0.2624],
        [0.7285, 0.2715],
        [0.7316, 0.2684],
        [0.7282, 0.2718],
        [0.7312, 0.2688],
        [0.7713, 0.2287],
        [0.7114, 0.2886],
        [0.7461, 0.2539],
        [0.7513, 0.2487],
        [0.7420, 0.2580],
        [0.7439, 0.2561],
        [0.7412, 0.2588],
        [0.7507, 0.2493],
        [0.7540, 0.2460],
        [0.7012, 0.2988],
        [0.7010, 0.2990],
        [0.7012, 0.2988],
        [0.7012, 0.2988],
        [0.7011, 0.2989],
        [0.7012, 0.2988],
        [0.7005, 0.2995],
        [0.7259, 0.2741],
        [0.7280, 0.2720],
        [0.7234, 0.2766],
        [0.7

In [43]:
torch.Tensor(np.squeeze(np.load('logs/exp2020-06-27T18:20:43.181813/0_rel_graph_grad.npy'))[0])

tensor([[ 2.3916e-02, -2.3916e-02],
        [ 4.6865e-02, -4.6865e-02],
        [ 2.3737e-03, -2.3737e-03],
        [ 5.2621e-04, -5.2621e-04],
        [ 4.8675e-03, -4.8675e-03],
        [ 2.5948e-02, -2.5948e-02],
        [ 2.2249e-02, -2.2249e-02],
        [-6.3811e-03,  6.3811e-03],
        [-1.6867e-02,  1.6867e-02],
        [-1.5393e-05,  1.5393e-05],
        [-1.2491e-04,  1.2491e-04],
        [-1.4796e-02,  1.4796e-02],
        [-2.1448e-04,  2.1448e-04],
        [-3.7762e-02,  3.7762e-02],
        [-6.6433e-02,  6.6433e-02],
        [-1.5416e-02,  1.5416e-02],
        [-6.8907e-02,  6.8907e-02],
        [-2.8558e-02,  2.8558e-02],
        [-4.3664e-02,  4.3664e-02],
        [-2.3036e-04,  2.3036e-04],
        [-9.6356e-02,  9.6356e-02],
        [-2.9030e-02,  2.9030e-02],
        [-1.7885e-02,  1.7885e-02],
        [-3.3899e-02,  3.3899e-02],
        [-2.9378e-02,  2.9378e-02],
        [-2.8083e-02,  2.8083e-02],
        [-2.0533e-02,  2.0533e-02],
        [-1.2789e-03,  1.278

In [61]:
a=torch.Tensor([[[1,2,3],[4,5,6]]])
a.size()

torch.Size([1, 2, 3])

In [62]:
b=torch.Tensor([[[1],[0]]])
b.size()

torch.Size([1, 2, 1])

In [2]:
from utils import *
from modules_causal import *

class MLPDecoder_Causal_1(nn.Module):
    """MLP decoder module."""

    def __init__(self, n_in_node, edge_types, msg_hid, msg_out, n_hid,
                 do_prob=0., skip_first=False, cuda=True, num_nodes=8, pred_steps=1):
        super(MLPDecoder_Causal_1, self).__init__()
        
        #TODO: only the last col of the original adj matrix will be trained   
        if cuda:
            self.rel_graph = torch.zeros((1, 1, num_nodes**2, edge_types), requires_grad=True, device="cuda")
#             self.zeros = torch.zeros((1, 1, (num_nodes-1)**2, edge_types), requires_grad=False, device="cuda")
#             self.all = torch.cat((self.zeros,self.rel_graph),dim=2)
        else:
            self.rel_graph = torch.zeros((1, 1, num_nodes*(num_nodes-1), edge_types), requires_grad=True)
#         import pdb;pdb.set_trace()
        
        nn.init.xavier_normal_(self.rel_graph)
        
        self.num_nodes = num_nodes
        self.edge_types = edge_types
#         for i in range(0,num_nodes*(num_nodes-1)+1, num_nodes-1):
#             self.rel_graph[:,:,i,:]=random.random()
   
            
        self.msg_fc1 = nn.ModuleList(
            [nn.Linear(2 * n_in_node, msg_hid) for _ in range(edge_types)])
        self.msg_fc2 = nn.ModuleList(
            [nn.Linear(msg_hid, msg_out) for _ in range(edge_types)])
        self.msg_out_shape = msg_out
        self.skip_first_edge_type = skip_first
        #dim small to large to small
        self.out_fc1 = nn.Linear(n_in_node + msg_out, n_hid)
        self.out_fc2 = nn.Linear(n_hid, n_hid)
        self.out_fc3 = nn.Linear(n_hid, n_in_node)

        print('Using learned interaction net decoder.')

        self.dropout_prob = do_prob

    def single_step_forward(self, single_timestep_inputs, rel_rec, rel_send, 
                            single_timestep_rel_type):

        # single_timestep_inputs has shape
        # [batch_size, num_timesteps, num_atoms, num_dims]

        # single_timestep_rel_type has shape:
        # [batch_size, num_timesteps, num_atoms*(num_atoms-1), num_edge_types]

        # Node2edge
        receivers = torch.matmul(rel_rec, single_timestep_inputs)
        senders = torch.matmul(rel_send, single_timestep_inputs)
        #pre_msg bs,timesteps, num_atoms*(num_atoms-1), 2
#         print('rel_rec',rel_rec)
#         print('rel_send', rel_send)

        pre_msg = torch.cat([senders, receivers], dim=-1)

        all_msgs = Variable(torch.zeros(pre_msg.size(0), pre_msg.size(1),
                                        pre_msg.size(2), self.msg_out_shape))
        if single_timestep_inputs.is_cuda:
            all_msgs = all_msgs.cuda()

        if self.skip_first_edge_type:
            start_idx = 1
        else:
            start_idx = 0
#         print('ffffff', single_timestep_inputs[0,0].size(), pre_msg[0,0].size())
#         print('ffffff', single_timestep_inputs[0,0], pre_msg[0,0])
            

#         test=torch.zeros((1,1,56,1)).cuda()  51,52,54,55
#         test[:,:,20,:]=1
#         test[:,:,27,:]=1
#         test[:,:,41,:]=1
#         test[:,:,48,:]=1

        # Run separate MLP for every edge type
        # NOTE: To exlude one edge type, simply offset range by 1
        for i in range(start_idx, len(self.msg_fc2)):
            print('start', i)
            
            msg = F.relu(self.msg_fc1[i](pre_msg))
            msg = F.dropout(msg, p=self.dropout_prob)
            msg = F.relu(self.msg_fc2[i](msg))
            #single_timestep_rel_type bs, pred_steps, #node*(#node-1), #edge_type
            #msg bs, pred_steps, #node*(#node-1), self.msg_out_shape=256
            msg_after = msg * single_timestep_rel_type[:, :, :, i:i + 1]
#             print('here',torch.nonzero(single_timestep_rel_type[:, :, :, i:i + 1]))
#             msg_after = msg * self.rel_graph[:, :, :, i:i + 1]
            all_msgs += msg_after
            

        # Aggregate all msgs to receiver
        #agg_msg bs, pred_steps, #node, self.msg_out_shape=256
        agg_msgs = all_msgs.transpose(-2, -1).matmul(rel_rec).transpose(-2, -1)
        agg_msgs = agg_msgs.contiguous()

        # Skip connection
        #msg bs, pred_steps, #node, self.msg_out_shape+1=257
        aug_inputs = torch.cat([single_timestep_inputs, agg_msgs], dim=-1)

        # Output MLP
        pred = F.dropout(F.relu(self.out_fc1(aug_inputs)), p=self.dropout_prob)
        pred = F.dropout(F.relu(self.out_fc2(pred)), p=self.dropout_prob)
        #in:256, out:1
        pred = self.out_fc3(pred)
#         import pdb; pdb.set_trace()

        # Predict position/velocity difference
        return single_timestep_inputs + pred, msg_after, msg

    def forward(self, inputs, rel_rec, rel_send, tau, hard, pred_steps):
        # NOTE: Assumes that we have the same graph across all samples.
#         logits = self.rel_graph # (inputs, rel_rec, rel_send)
        edges = gumbel_softmax(self.rel_graph, tau, hard)
        
        inputs = inputs.transpose(1, 2).contiguous()

#         sizes = [rel_type.size(0), inputs.size(1), rel_type.size(1),
#                  rel_type.size(2)]
        # NOTE: Assumes rel_type is constant (i.e. same across all time steps).
#         rel_type = rel_type.unsqueeze(1).expand(sizes)

        time_steps = inputs.size(1)
        assert (pred_steps <= time_steps)
        preds = []

        # Only take n-th timesteps as starting points (n: pred_steps) 5
        last_pred = inputs[:, 0::pred_steps, :, :]

#         curr_rel_type = rel_type[:, 0::pred_steps, :, :]
        # NOTE: Assumes rel_type is constant (i.e. same across all time steps).

        # Run n prediction steps
        for step in range(0, pred_steps): 
            last_pred, all_msgs, msg = self.single_step_forward(last_pred, rel_rec, rel_send, edges)
            preds.append(last_pred)

        sizes = [preds[0].size(0), preds[0].size(1) * pred_steps,
                 preds[0].size(2), preds[0].size(3)]

        output = Variable(torch.zeros(sizes))
        if inputs.is_cuda:
            output = output.cuda()

        # Re-assemble correct timeline
        for i in range(len(preds)): #10
            #5 fixed points, 10 each sequence. preds[i] means the ith of each sequence.
            output[:, i::pred_steps, :, :] = preds[i] 
        pred_all = output[:, :(inputs.size(1) - 1), :, :]

        return pred_all.transpose(1, 2).contiguous(), \
    self.rel_graph.squeeze(1).expand([inputs.size(0), self.num_nodes**2, self.edge_types]), all_msgs, msg

In [3]:
decoder = MLPDecoder_Causal_1(n_in_node=8,
                         edge_types=2,
                         msg_hid=256,
                         msg_out=256,
                         n_hid=256,
                         do_prob=0,
                         skip_first=True,
                         cuda=True,
                         num_nodes=7)
# rel_w = torch.load('logs/exp2020-07-04T02:16:59.482117/decoder.pt')[1]
# decoder.rel_graph = torch.Tensor(rel_w).cuda()
# decoder.load_state_dict(torch.load('logs/exp2020-07-04T02:16:59.482117/decoder.pt')[0])

Using learned interaction net decoder.


In [6]:
decoder.load_state_dict(torch.load('logs/exp2020-07-04T02:16:59.482117/decoder.pt')[0])

<All keys matched successfully>

In [28]:
decoder.rel_graph =torch.load('logs/exp2020-07-04T02:16:59.482117/decoder.pt')[1]
decoder.rel_graph.argmax(-1).view((7,7))

tensor([[0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 1, 1, 0, 0, 0],
        [0, 0, 0, 0, 0, 1, 0]], device='cuda:0')

In [9]:
train_loader, valid_loader, test_loader = load_my_data(batch_size=128, 
                                                       suffix='_causal_vel')


# Generate off-diagonal interaction graph, ones with only zeros on diagonal
off_diag = np.ones([7, 7]) #- np.eye(7)
# This is not adjacency matrix since it's 56*8, not 8*8!
rel_rec = np.array(encode_onehot(np.where(off_diag)[0]), dtype=np.float32)
rel_send = np.array(encode_onehot(np.where(off_diag)[1]), dtype=np.float32)
rel_rec = torch.FloatTensor(rel_rec)
rel_send = torch.FloatTensor(rel_send)

KeyboardInterrupt: 

In [268]:
decoder.cuda()
rel_rec = rel_rec.cuda()
rel_send = rel_send.cuda()
from utils import *

for batch_idx, (data, relations) in enumerate(train_loader):
    if batch_idx<10:
        data, relations = data.cuda(), relations.cuda()
        output, logits, all_msgs, msg = decoder(data, rel_rec, rel_send,
                                 0.5, True, 1)
#         print(output.size(), msg.size())
#         print(msg[0,0,48], all_msgs[0,0,48])
        print('jjjj',batch_idx, output[0,-2:,:,0], '\n',data[0,-2:,1:,0])
        target = data[:, :, 1:, :] 
        loss_nll = nll_gaussian(output, target, 5e-5)
        print('LOSS', loss_nll)
    else:
        break

start 1
jjjj 0 tensor([[-0.0300, -0.0412, -0.0526, -0.0645, -0.0766, -0.0889, -0.1013, -0.1139,
         -0.1266, -0.1398, -0.1534, -0.1663, -0.1789, -0.1915, -0.2040, -0.2169,
         -0.2300, -0.2433],
        [-0.0616, -0.0616, -0.0624, -0.0647, -0.0688, -0.0742, -0.0804, -0.0885,
         -0.0970, -0.1065, -0.1168, -0.1281, -0.1407, -0.1542, -0.1690, -0.1851,
         -0.2031, -0.2225]], device='cuda:0', grad_fn=<SelectBackward>) 
 tensor([[-0.0272, -0.0398, -0.0523, -0.0649, -0.0774, -0.0900, -0.1025, -0.1151,
         -0.1276, -0.1402, -0.1527, -0.1653, -0.1778, -0.1904, -0.2029, -0.2155,
         -0.2280, -0.2406],
        [-0.0644, -0.0632, -0.0633, -0.0647, -0.0674, -0.0714, -0.0767, -0.0833,
         -0.0911, -0.1003, -0.1108, -0.1226, -0.1357, -0.1501, -0.1658, -0.1828,
         -0.2011, -0.2207]], device='cuda:0')
LOSS tensor(0.5973, device='cuda:0', grad_fn=<DivBackward0>)
start 1
jjjj 1 tensor([[-0.0270, -0.0203, -0.0137, -0.0069, -0.0002,  0.0065,  0.0129,  0.0193,
    

In [270]:
edges = decoder.rel_graph.softmax(-1)
edges

tensor([[[[0.6803, 0.3197],
          [0.6883, 0.3117],
          [0.6914, 0.3086],
          [0.6982, 0.3018],
          [0.6948, 0.3052],
          [0.6890, 0.3110],
          [0.6933, 0.3067],
          [0.6903, 0.3097],
          [0.6831, 0.3169],
          [0.6981, 0.3019],
          [0.6968, 0.3032],
          [0.6921, 0.3079],
          [0.6971, 0.3029],
          [0.6995, 0.3005],
          [0.6928, 0.3072],
          [0.6887, 0.3113],
          [0.6826, 0.3174],
          [0.6694, 0.3306],
          [0.6728, 0.3272],
          [0.6957, 0.3043],
          [0.6897, 0.3103],
          [0.6852, 0.3148],
          [0.6906, 0.3094],
          [0.6727, 0.3273],
          [0.6871, 0.3129],
          [0.6751, 0.3249],
          [0.6903, 0.3097],
          [0.6907, 0.3093],
          [0.6980, 0.3020],
          [0.6975, 0.3025],
          [0.6998, 0.3002],
          [0.6941, 0.3059],
          [0.6981, 0.3019],
          [0.6991, 0.3009],
          [0.6964, 0.3036],
          [0.6700, 0

In [18]:
rel_w.shape

(352, 1, 1, 56, 2)

In [84]:
a=np.array([[1,2,3],[3,4,5]])
a.reshape(-1,6)

array([[1, 2, 3, 3, 4, 5]])

In [28]:
f = np.load('data/edges_train_my.npy')
print(f.shape)
# for i in range(100):
#     print(f[i,:,1])

(45000, 8, 8)


In [161]:
#[s,c,friction,t,m,vel,loc]
torch.Tensor(np.squeeze(np.load('logs/exp2020-06-30T21:28:03.944345/130_rel_graph.npy'))[0]).softmax(-1)

tensor([[0.6996, 0.3004],
        [0.6988, 0.3012],
        [0.6934, 0.3066],
        [0.7002, 0.2998],
        [0.6991, 0.3009],
        [0.6969, 0.3031],
        [0.6998, 0.3002],
        [0.6993, 0.3007],
        [0.6998, 0.3002],
        [0.6994, 0.3006],
        [0.7002, 0.2998],
        [0.6990, 0.3010],
        [0.7005, 0.2995],
        [0.6975, 0.3025],
        [0.6975, 0.3025],
        [0.6982, 0.3018],
        [0.6867, 0.3133],
        [0.6986, 0.3014],
        [0.6967, 0.3033],
        [0.6998, 0.3002],
        [0.6982, 0.3018],
        [0.6973, 0.3027],
        [0.6989, 0.3011],
        [0.6933, 0.3067],
        [0.6990, 0.3010],
        [0.6935, 0.3065],
        [0.6974, 0.3026],
        [0.6959, 0.3041],
        [0.7000, 0.3000],
        [0.6996, 0.3004],
        [0.6969, 0.3031],
        [0.6991, 0.3009],
        [0.6995, 0.3005],
        [0.6985, 0.3015],
        [0.6975, 0.3025],
        [0.6360, 0.3640],
        [0.6223, 0.3777],
        [0.4439, 0.5561],
        [0.4

In [18]:
#self loop, one_hot
#not self loop, one_hot; not self loop, no one_hot -> velocity all zeros??
#if all zeros, should predict vel=0

#tau=0.5; kl smaller; roll out predict step more
#study influnce of delta theta and mu
#[s,c,friction,t,m,vel,loc]
#generate more toy data

#toy 4
torch.Tensor(np.load('logs/exp2020-07-04T21:07:44.112351/190_rel_graph.npy')[-1]).argmax(-1).view(7,7)

tensor([[0, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 1, 0]])

In [20]:
#toy 3
torch.Tensor(np.load('logs/exp2020-07-04T21:13:41.574115/160_rel_graph.npy')[-1]).argmax(-1).view(7,7)

tensor([[0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 1, 0, 0]])

In [21]:
#toy 6
torch.Tensor(np.load('logs/exp2020-07-04T21:15:17.252488/160_rel_graph.npy')[-1]).argmax(-1).view(7,7)

tensor([[0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 1, 0]])

In [41]:
#sparsity increase, set to 0 and compare loss (find loss lower bound)
torch.Tensor(np.load('logs/exp2020-07-02T22:38:52.295235/490_rel_graph.npy')[-1]).argmax(-1).view(7,7)#softmax(-1).view(7,7,2)

tensor([[[0.7002, 0.2998],
         [0.7019, 0.2981],
         [0.6978, 0.3022],
         [0.7049, 0.2951],
         [0.7011, 0.2989],
         [0.7007, 0.2993],
         [0.7004, 0.2996]],

        [[0.7021, 0.2979],
         [0.6992, 0.3008],
         [0.6840, 0.3160],
         [0.7051, 0.2949],
         [0.7008, 0.2992],
         [0.7006, 0.2994],
         [0.7009, 0.2991]],

        [[0.7006, 0.2994],
         [0.6989, 0.3011],
         [0.6951, 0.3049],
         [0.6171, 0.3829],
         [0.6938, 0.3062],
         [0.6979, 0.3021],
         [0.6971, 0.3029]],

        [[0.7018, 0.2982],
         [0.7008, 0.2992],
         [0.6872, 0.3128],
         [0.6997, 0.3003],
         [0.6990, 0.3010],
         [0.6998, 0.3002],
         [0.6996, 0.3004]],

        [[0.7017, 0.2983],
         [0.7020, 0.2980],
         [0.6818, 0.3182],
         [0.7018, 0.2982],
         [0.7007, 0.2993],
         [0.7005, 0.2995],
         [0.7002, 0.2998]],

        [[0.6974, 0.3026],
         [0.6866, 

In [42]:
#toy 2: prdicts b out with high prob but <0.01 for a
torch.Tensor(np.load('logs/exp2020-07-07T04:13:10.396214/140_rel_graph.npy')[-1]).argmax(-1).view(7,7)

tensor([[0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 1, 1, 0]])

In [45]:
#toy 7
import torch
import numpy as np
torch.Tensor(np.load('logs/exp2020-07-07T04:20:24.869651/`60_rel_graph.npy')[-1]).argmax(-1).view(7,7)

FileNotFoundError: [Errno 2] No such file or directory: 'logs/exp2020-07-07T04:20:24.869651/`60_rel_graph.npy'

In [47]:
#toy 5: training for many vars prob to decrease
torch.Tensor(np.load('logs/exp2020-07-07T04:15:46.169058/240_rel_graph.npy')[-1]).argmax(-1).view(7,7)

FileNotFoundError: [Errno 2] No such file or directory: 'logs/exp2020-07-07T04:15:46.169058/240_rel_graph.npy'

In [60]:
x=[1,2,3]
x[0::3]

[1]

In [25]:
#toy 1
torch.Tensor(np.load('logs/exp2020-07-04T21:10:35.626412/180_rel_graph.npy')[-1]).argmax(-1).view(7,7)

tensor([[0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 1, 0, 0]])

In [35]:
#toy 1
torch.Tensor(np.load('logs/exp2020-07-03T02:00:19.133317/660_rel_graph.npy')[-1]).argmax(-1).view(7,6)

tensor([[0, 0, 0, 0, 0, 1],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0, 0],
        [0, 1, 0, 1, 1, 1]])

In [165]:
torch.save([decoder.state_dict(), rel_w],'test.pt')

In [248]:
step=19
u0=0
v0=0
g=9.8
mus=[0.001, 0.05, 0.1, 0.5, 0.98]
mu=mus[4]
thetas= [math.pi/90, math.pi/6,math.pi/4,math.pi/3,math.pi*44/45]
interval=2


L_vars=[]
V_vars=[]

for mu in mus:
    L=[]
    V=[]
    for theta in thetas:
        loc = np.zeros(step)
        loc[0] = u0
        vel = np.zeros(step)
        vel[0] = v0
        for i in range(1, step):
            loc[i]=loc[i-1]+vel[i-1]*interval+0.5*g*(np.sin(theta)-np.cos(theta)*mu)*(interval**2)
            vel[i] = vel[i-1]+g*(np.sin(theta)-np.cos(theta)*mu)
        V.append(vel)
        L.append(loc)
    V=np.array(V)    
    L=np.array(L)  
    V_vars.append(V.var(0))
    L_vars.append(L.var(0))

np.array(V_vars).mean(0), np.array(L_vars).mean(0)

(array([   0.        ,   17.72001552,   70.88006207,  159.48013966,
         283.52024829,  443.00038795,  637.92055865,  868.28076039,
        1134.08099316, 1435.32125697, 1772.00155181, 2144.12187769,
        2551.68223461, 2994.68262256, 3473.12304155, 3987.00349158,
        4536.32397264, 5121.08448474, 5741.28502787]),
 array([0.00000000e+00, 7.08800621e+01, 6.37920559e+02, 2.55168223e+03,
        7.08800621e+03, 1.59480140e+04, 3.12581074e+04, 5.55699687e+04,
        9.18605604e+04, 1.43532126e+05, 2.14412188e+05, 3.08753550e+05,
        4.31234298e+05, 5.86957794e+05, 7.81452684e+05, 1.02067289e+06,
        1.31099763e+06, 1.65923137e+06, 2.07260390e+06]))

In [70]:
torch.Tensor(np.load('logs/exp2020-07-11T17:10:45.016169/180_rel_graph.npy')[-1]).argmax(-1).view(8,8)


tensor([[1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1],
        [0, 1, 1, 0, 0, 1, 1, 0],
        [0, 0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1],
        [0, 0, 1, 1, 0, 0, 1, 0],
        [0, 0, 1, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0]])

In [3]:
import torch
import numpy as np
#sin cos
torch.Tensor(np.load('logs/exp2020-07-14T13:55:08.770691/560_rel_graph.npy')[-1]).argmax(-1).view(9,9)

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 1, 1, 0, 0, 1, 0, 1],
        [0, 0, 1, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [52]:
torch.Tensor(np.load('logs/exp2020-07-16T19:00:03.362900/10_rel_graph.npy')[-1]).argmax(-1).view(9,9)

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 1, 1, 0, 0, 1, 0, 1],
        [0, 0, 1, 1, 0, 1, 0, 0, 1],
        [0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [50]:
#SHO
torch.Tensor(np.load('logs/exp2020-07-14T22:09:52.789567/690_rel_graph.npy')[-1]).argmax(-1).view(10,10)

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 1, 0, 1, 0, 0, 0, 0, 0, 1],
        [1, 0, 1, 0, 0, 0, 0, 0, 0, 1],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [42]:
#toy 9
torch.Tensor(np.load('logs/exp2020-07-14T18:35:30.572260/560_rel_graph.npy')[-1]).argmax(-1).view(17,17)

tensor([[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0],
        [1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0],
        [1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0],
        [0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0],
        [0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1],
        [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
        [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
        [0, 1, 0, 0, 0, 

In [47]:
#gravity
torch.Tensor(np.load('logs/exp2020-07-14T22:24:59.531529/500_rel_graph.npy')[-1]).argmax(-1).view(12,12)

tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
        [0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0],
        [0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0],
        [1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0]])

In [8]:
torch.Tensor(np.load('logs/exp2020-07-16T19:02:57.867514/300_rel_graph.npy')[-1]).softmax(-1).view(9,9,2)

tensor([[[0.6685, 0.3315],
         [0.6875, 0.3125],
         [0.6166, 0.3834],
         [0.6898, 0.3102],
         [0.7279, 0.2721],
         [0.6833, 0.3167],
         [0.6977, 0.3023],
         [0.6461, 0.3539],
         [0.6808, 0.3192]],

        [[0.7337, 0.2663],
         [0.7290, 0.2710],
         [0.6590, 0.3410],
         [0.7243, 0.2757],
         [0.7520, 0.2480],
         [0.7433, 0.2567],
         [0.7043, 0.2957],
         [0.6922, 0.3078],
         [0.7330, 0.2670]],

        [[0.6587, 0.3413],
         [0.7299, 0.2701],
         [0.7225, 0.2775],
         [0.7125, 0.2875],
         [0.7357, 0.2643],
         [0.6903, 0.3097],
         [0.7166, 0.2834],
         [0.6636, 0.3364],
         [0.7214, 0.2786]],

        [[0.7351, 0.2649],
         [0.7070, 0.2930],
         [0.7008, 0.2992],
         [0.7309, 0.2691],
         [0.7159, 0.2841],
         [0.7526, 0.2474],
         [0.7357, 0.2643],
         [0.7066, 0.2934],
         [0.7098, 0.2902]],

        [[0.6670, 0.