In [1]:
import torch
import numpy as np

In [9]:
#(1, 1, 64, 2)
grads=np.load('logs/exp2020-07-26T15:07:07.802441/20_rel_graph_grad.npy')
#grouped, control_constrain=0.0
torch.load('logs/exp2020-07-26T15:07:07.802441/20_decoder.pt')[1].softmax(-1)

tensor([[[[0.9000, 0.1000],
          [0.9000, 0.1000],
          [0.8995, 0.1005],
          [0.9000, 0.1000],
          [0.9000, 0.1000],
          [0.9000, 0.1000],
          [0.9006, 0.0994],
          [0.9006, 0.0994],
          [0.9000, 0.1000],
          [0.9000, 0.1000],
          [0.9000, 0.1000],
          [0.9000, 0.1000],
          [0.9000, 0.1000],
          [0.9000, 0.1000],
          [0.9005, 0.0995],
          [0.9005, 0.0995],
          [0.9000, 0.1000],
          [0.9000, 0.1000],
          [0.8994, 0.1006],
          [0.9005, 0.0995],
          [0.9000, 0.1000],
          [0.9000, 0.1000],
          [0.9004, 0.0996],
          [0.9005, 0.0995],
          [0.8994, 0.1006],
          [0.8994, 0.1006],
          [0.8997, 0.1003],
          [0.9009, 0.0991],
          [0.9000, 0.1000],
          [0.9000, 0.1000],
          [0.9006, 0.0994],
          [0.8994, 0.1006],
          [0.9000, 0.1000],
          [0.9000, 0.1000],
          [0.9000, 0.1000],
          [0.8985, 0

In [3]:
grads=np.load('logs/exp2020-07-27T18:26:29.872853/18_rel_graph_grad.npy')


In [37]:
nodes = torch.load('logs/exp2020-07-28T03:33:40.531962/10_nodes.pt')
nodes
#nodes.unique(return_counts=True) #tensor([17,  7, 21, 67, 12, 22], device='cuda:0'))

tensor([0, 1, 2, 3, 4, 5, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0], device='cuda:0')

In [40]:
grads=np.load('logs/exp2020-07-28T03:33:40.531962/10_rel_graph_grad.npy')
np.reshape(np.abs(grads[-1]).sum(-1), (8,8)).sum(0)


array([  74.55238 ,   45.805107,  926.23315 , 4471.435   ,  155.88333 ,
        105.58284 ,   85.281944,  269.40475 ], dtype=float32)

In [35]:
a=np.array([[1,2],[3,4]])
a.sum(0)

array([4, 6])

In [12]:
nodes = torch.load('logs/exp2020-07-28T03:36:52.606736/140_nodes.pt')
nodes.unique(return_counts=True)

(tensor([0, 1, 2, 3, 4, 5], device='cuda:0'),
 tensor([24, 31, 18, 27, 28, 18], device='cuda:0'))

In [45]:
torch.load('logs/exp2020-07-28T15:46:17.578695/0_decoder.pt')[1].softmax(-1)

tensor([[[[0.9003, 0.0997],
          [0.9003, 0.0997],
          [0.9003, 0.0997],
          [0.9009, 0.0991],
          [0.9001, 0.0999],
          [0.9004, 0.0996],
          [0.8998, 0.1002],
          [0.8994, 0.1006],
          [0.8991, 0.1009],
          [0.8981, 0.1019],
          [0.8984, 0.1016],
          [0.9008, 0.0992],
          [0.8984, 0.1016],
          [0.8996, 0.1004],
          [0.8971, 0.1029],
          [0.8960, 0.1040],
          [0.8681, 0.1319],
          [0.8755, 0.1245],
          [0.8476, 0.1524],
          [0.8323, 0.1677],
          [0.8731, 0.1269],
          [0.8742, 0.1258],
          [0.8475, 0.1525],
          [0.8567, 0.1433],
          [0.8686, 0.1314],
          [0.8654, 0.1346],
          [0.8271, 0.1729],
          [0.8340, 0.1660],
          [0.8551, 0.1449],
          [0.8575, 0.1425],
          [0.8252, 0.1748],
          [0.8180, 0.1820],
          [0.8994, 0.1006],
          [0.8992, 0.1008],
          [0.8985, 0.1015],
          [0.9012, 0

In [43]:
#grouped, control_constrain=1.0
torch.load('logs/exp2020-07-26T02:56:28.869431/20_decoder.pt')[1].softmax(-1)

tensor([[[[0.9000, 0.1000],
          [0.9000, 0.1000],
          [0.9000, 0.1000],
          [0.9000, 0.1000],
          [0.9000, 0.1000],
          [0.9000, 0.1000],
          [0.9000, 0.1000],
          [0.9000, 0.1000],
          [0.9000, 0.1000],
          [0.9000, 0.1000],
          [0.9000, 0.1000],
          [0.9000, 0.1000],
          [0.9000, 0.1000],
          [0.9001, 0.0999],
          [0.9000, 0.1000],
          [0.9000, 0.1000],
          [0.9000, 0.1000],
          [0.9000, 0.1000],
          [0.9001, 0.0999],
          [0.9000, 0.1000],
          [0.9000, 0.1000],
          [0.9000, 0.1000],
          [0.8999, 0.1001],
          [0.9000, 0.1000],
          [0.9001, 0.0999],
          [0.9000, 0.1000],
          [0.9000, 0.1000],
          [0.9000, 0.1000],
          [0.9001, 0.0999],
          [0.9001, 0.0999],
          [0.9001, 0.0999],
          [0.9005, 0.0995],
          [0.9001, 0.0999],
          [0.9000, 0.1000],
          [0.9000, 0.1000],
          [0.9000, 0

In [12]:
# grads=np.load('logs/exp2020-07-18T14:48:13.747535/250_rel_graph_grad.npy')
torch.load('logs/exp2020-07-25T22:03:55.202618/120_decoder.pt')[1].softmax(-1)

tensor([[[[0.8941, 0.1059],
          [0.8953, 0.1047],
          [0.8907, 0.1093],
          [0.8923, 0.1077],
          [0.8965, 0.1035],
          [0.8940, 0.1060],
          [0.8960, 0.1040],
          [0.8934, 0.1066],
          [0.8954, 0.1046],
          [0.8951, 0.1049],
          [0.8962, 0.1038],
          [0.8875, 0.1125],
          [0.8963, 0.1037],
          [0.8988, 0.1012],
          [0.8961, 0.1039],
          [0.8953, 0.1047],
          [0.8429, 0.1571],
          [0.8515, 0.1485],
          [0.8082, 0.1918],
          [0.8117, 0.1883],
          [0.8557, 0.1443],
          [0.8520, 0.1480],
          [0.8488, 0.1512],
          [0.8417, 0.1583],
          [0.8605, 0.1395],
          [0.8476, 0.1524],
          [0.7448, 0.2552],
          [0.8223, 0.1777],
          [0.8570, 0.1430],
          [0.8603, 0.1397],
          [0.8337, 0.1663],
          [0.8348, 0.1652],
          [0.8953, 0.1047],
          [0.8960, 0.1040],
          [0.8898, 0.1102],
          [0.8859, 0

In [26]:
#1[0]
torch.load('logs/exp2020-07-27T21:27:03.086430/40_decoder.pt')[1].softmax(-1)

tensor([[[[0.8994, 0.1006],
          [0.8996, 0.1004],
          [0.8992, 0.1008],
          [0.9003, 0.0997],
          [0.8991, 0.1009],
          [0.8993, 0.1007],
          [0.8999, 0.1001],
          [0.8996, 0.1004],
          [0.8985, 0.1015],
          [0.8991, 0.1009],
          [0.8986, 0.1014],
          [0.8989, 0.1011],
          [0.8995, 0.1005],
          [0.8984, 0.1016],
          [0.8974, 0.1026],
          [0.8986, 0.1014],
          [0.8711, 0.1289],
          [0.8708, 0.1292],
          [0.8429, 0.1571],
          [0.8241, 0.1759],
          [0.8727, 0.1273],
          [0.8707, 0.1293],
          [0.8537, 0.1463],
          [0.8466, 0.1534],
          [0.8628, 0.1372],
          [0.8549, 0.1451],
          [0.7839, 0.2161],
          [0.8297, 0.1703],
          [0.8659, 0.1341],
          [0.8639, 0.1361],
          [0.8281, 0.1719],
          [0.8162, 0.1838],
          [0.8989, 0.1011],
          [0.8995, 0.1005],
          [0.8978, 0.1022],
          [0.8955, 0

In [24]:
#1[3]
torch.load('logs/exp2020-07-27T23:37:40.619109/20_decoder.pt')[1].softmax(-1)

tensor([[[[0.6358, 0.3642],
          [0.6326, 0.3674],
          [0.5839, 0.4161],
          [0.6576, 0.3424],
          [0.6500, 0.3500],
          [0.6099, 0.3901],
          [0.6709, 0.3291],
          [0.6213, 0.3787],
          [0.6234, 0.3766],
          [0.6374, 0.3626],
          [0.6736, 0.3264],
          [0.6068, 0.3932],
          [0.6550, 0.3450],
          [0.7089, 0.2911],
          [0.6814, 0.3186],
          [0.6611, 0.3389],
          [0.5565, 0.4435],
          [0.5727, 0.4273],
          [0.5101, 0.4899],
          [0.5670, 0.4330],
          [0.6010, 0.3990],
          [0.5790, 0.4210],
          [0.5856, 0.4144],
          [0.5495, 0.4505],
          [0.5738, 0.4262],
          [0.5476, 0.4524],
          [0.4734, 0.5266],
          [0.5915, 0.4085],
          [0.5676, 0.4324],
          [0.5867, 0.4133],
          [0.5860, 0.4140],
          [0.5554, 0.4446],
          [0.6533, 0.3467],
          [0.6655, 0.3345],
          [0.5827, 0.4173],
          [0.6010, 0

In [17]:
grads=np.load('logs/exp2020-07-14T13:55:08.770691/250_rel_graph_grad.npy')
print((np.var(grads, axis=0)/np.mean(grads, axis=0))[0,0,-16:,:])

[[-2.58565105e-05 -1.48539375e-05]
 [-4.29031886e-02  2.17904244e-02]
 [-3.63917497e-05 -2.13175153e-05]
 [-6.05207402e-04  6.86264550e-03]
 [ 5.81595195e-05  8.63612586e-05]
 [-1.08603757e-07 -9.17780909e-08]
 [ 1.92072039e-05 -1.96779129e-05]
 [-2.54283285e+00  2.54268456e+00]
 [-4.00848120e-01  4.00834173e-01]
 [ 1.49848640e+00 -1.49849761e+00]
 [-1.65085745e+00  1.65084934e+00]
 [-3.55093217e+00  3.55061293e+00]
 [ 9.22753990e-01 -9.22737896e-01]
 [ 7.56168962e-01 -7.56154001e-01]
 [-3.01487744e-01  3.01488370e-01]
 [ 3.26323462e+00 -3.26335430e+00]]


In [19]:
grads=np.load('logs/exp2020-07-16T19:05:05.312565/250_rel_graph_grad.npy')
print((np.var(grads, axis=0)/np.mean(grads, axis=0))[0,0,-16:,:])

[[-0.09921756  0.09921755]
 [-1.0995629   1.0995629 ]
 [-0.07563373  0.07563376]
 [-0.27537522  0.27537522]
 [-0.12072898  0.12072899]
 [-0.0872428   0.08724279]
 [-0.12816837  0.12816834]
 [-0.20535973  0.20535971]
 [-0.03878377  0.03878377]
 [-1.0057598   1.0057598 ]
 [-0.15424001  0.15424   ]
 [-0.17178072  0.17178077]
 [-0.05697478  0.05697478]
 [-0.05754867  0.05754868]
 [-0.04651249  0.04651247]
 [-0.14415482  0.14415485]]


In [24]:
grads=np.load('logs/exp2020-07-21T21:46:59.003692/200_rel_graph_grad.npy')
print((np.var(grads, axis=0)/np.mean(grads, axis=0))[0,0,-16:,:])

[[ 1.0225382e+00 -1.0225383e+00]
 [ 1.5816960e+03 -1.5816958e+03]
 [-3.5002086e-01  3.5002089e-01]
 [-3.4555912e-01  3.4555894e-01]
 [ 2.0453544e-01 -2.0453541e-01]
 [ 2.1438594e+00 -2.1438594e+00]
 [ 4.6631036e+02 -4.6631036e+02]
 [ 6.0304352e+02 -6.0304352e+02]
 [ 1.2828732e-01 -1.2828730e-01]
 [-1.1683205e+02  1.1683223e+02]
 [-3.4345526e-01  3.4345526e-01]
 [-7.5753766e-01  7.5753754e-01]
 [-3.4006029e-01  3.4006035e-01]
 [-5.9367830e-01  5.9367830e-01]
 [ 6.0777466e+02 -6.0777386e+02]
 [-1.6225598e+03  1.6225598e+03]]


In [25]:
grads=np.load('logs/exp2020-07-21T21:46:47.864056/200_rel_graph_grad.npy')
print((np.var(grads, axis=0)/np.mean(grads, axis=0))[0,0,-16:,:])

[[-3.4328866e-01  3.4328866e-01]
 [-4.0274481e+02  4.0274603e+02]
 [-3.7801638e-01  3.7801641e-01]
 [-5.1758897e-02  5.1758897e-02]
 [-4.3250635e-01  4.3250623e-01]
 [-4.9331802e-01  4.9331802e-01]
 [-1.6924600e+03  1.6924600e+03]
 [-2.3483669e+02  2.3484052e+02]
 [-3.4155548e-01  3.4155548e-01]
 [ 3.5836432e+02 -3.5836426e+02]
 [-1.9984968e-01  1.9984968e-01]
 [-3.3631378e-01  3.3631387e-01]
 [-3.4555072e-01  3.4555072e-01]
 [ 1.2820079e+00 -1.2820076e+00]
 [ 5.4021821e+03 -5.4021792e+03]
 [ 3.0694318e+02 -3.0694318e+02]]


In [ ]:
#Current renormalization has problems
1 10 -> -1 1 -> -1  4/21 -1
1 20    1 20 -> 4/21 -1  1

-1 18/19 -1
-1 1