In [1]:
import numpy as np
import torch

In [5]:
#bs=6, not grouped
torch.load('logs/exp2020-07-27T18:07:50.586449/80_decoder.pt')[1].softmax(-1)[:,:,-16:,:]

tensor([[[[0.9000, 0.1000],
          [0.9001, 0.0999],
          [0.0279, 0.9721],
          [0.0373, 0.9627],
          [0.9002, 0.0998],
          [0.9000, 0.1000],
          [0.9325, 0.0675],
          [0.5767, 0.4233],
          [0.9001, 0.0999],
          [0.9000, 0.1000],
          [0.0497, 0.9503],
          [0.0761, 0.9239],
          [0.9005, 0.0995],
          [0.8962, 0.1038],
          [0.3945, 0.6055],
          [0.9695, 0.0305]]]], device='cuda:0', grad_fn=<SliceBackward>)

In [3]:
torch.load('logs/exp2020-08-10T19:16:41.894627_train-bs_144_control-constraint_1.0_grouped_suffix_causal_vel_grouped_46656/best_decoder.pt')[1].softmax(-1)[:,:,-16:,:]

tensor([[[[0.8791, 0.1209],
          [0.8941, 0.1059],
          [0.0918, 0.9082],
          [0.1401, 0.8599],
          [0.8934, 0.1066],
          [0.8728, 0.1272],
          [0.7332, 0.2668],
          [0.2533, 0.7467],
          [0.4300, 0.5700],
          [0.3949, 0.6051],
          [0.1948, 0.8052],
          [0.2326, 0.7674],
          [0.4709, 0.5291],
          [0.5813, 0.4187],
          [0.1622, 0.8378],
          [0.6431, 0.3569]]]], device='cuda:0', grad_fn=<SliceBackward>)

In [5]:
np.load('logs/exp2020-07-27T18:07:50.586449/0_rel_graph_grad.npy')[0][:,:,-16:,:]

array([[[[-7087.4097   ,  7087.4106   ],
         [-9696.729    ,  9696.7295   ],
         [-7427.7764   ,  7427.7754   ],
         [-2695.5356   ,  2695.5356   ],
         [  -14.2714815,    14.272117 ],
         [-4458.6934   ,  4458.6934   ],
         [-1710.9625   ,  1710.9626   ],
         [  -36.284153 ,    36.284157 ],
         [-4761.8525   ,  4761.8516   ],
         [-5743.991    ,  5743.991    ],
         [-2348.3225   ,  2348.3242   ],
         [-2734.0574   ,  2734.0574   ],
         [-1480.2396   ,  1480.2396   ],
         [-2370.0496   ,  2370.0496   ],
         [ -925.2566   ,   925.25665  ],
         [-1889.922    ,  1889.9221   ]]]], dtype=float32)

In [53]:
#bs=128, not grouped
torch.load('logs/exp2020-07-28T21:04:42.546747/40_decoder.pt')[1].softmax(-1)[:,:,-16:,:]

tensor([[[[0.6154, 0.3846],
          [0.5731, 0.4269],
          [0.3279, 0.6721],
          [0.2923, 0.7077],
          [0.5767, 0.4233],
          [0.5786, 0.4214],
          [0.5827, 0.4173],
          [0.3291, 0.6709],
          [0.5968, 0.4032],
          [0.6210, 0.3790],
          [0.2608, 0.7392],
          [0.2722, 0.7278],
          [0.5973, 0.4027],
          [0.5862, 0.4138],
          [0.3560, 0.6440],
          [0.6264, 0.3736]]]], device='cuda:0', grad_fn=<SliceBackward>)

In [54]:
np.load('logs/exp2020-07-28T21:04:42.546747/40_rel_graph_grad.npy')[0][:,:,-16:,:]

array([[[[ -0.50085926,   0.5008594 ],
         [ -0.5117245 ,   0.5117245 ],
         [ 39.787582  , -39.787582  ],
         [  0.6597771 ,  -0.65977716],
         [ -0.42693114,   0.4269313 ],
         [ -0.1384466 ,   0.13844657],
         [  3.4837205 ,  -3.4837205 ],
         [  6.111769  ,  -6.1117687 ],
         [ -0.5060744 ,   0.5060745 ],
         [ -0.49383447,   0.49383435],
         [ -2.8172255 ,   2.8172262 ],
         [ -0.39160353,   0.39160365],
         [ -0.52959114,   0.52959096],
         [ -0.49897438,   0.49897444],
         [ -0.80360776,   0.803608  ],
         [ -0.49185205,   0.49185184]]]], dtype=float32)

In [6]:
#grouped, no constraint
torch.load('logs/exp2020-07-27T18:26:29.872853/30_decoder.pt')[1].softmax(-1)[:,:,-16:,:]

tensor([[[[0.8999, 0.1001],
          [0.9003, 0.0997],
          [0.0058, 0.9942],
          [0.0052, 0.9948],
          [0.9001, 0.0999],
          [0.9219, 0.0781],
          [0.9450, 0.0550],
          [0.8312, 0.1688],
          [0.9005, 0.0995],
          [0.9005, 0.0995],
          [0.0167, 0.9833],
          [0.0166, 0.9834],
          [0.9012, 0.0988],
          [0.8605, 0.1395],
          [0.5509, 0.4491],
          [0.9787, 0.0213]]]], device='cuda:0', grad_fn=<SliceBackward>)

In [9]:
np.load('logs/exp2020-07-27T18:26:29.872853/30_rel_graph_grad.npy')[0][:,:,-16:,:]

array([[[[-1.74129003e-04,  1.74140179e-04],
         [ 3.20672843e-04, -3.20713822e-04],
         [-4.75241318e-02,  4.75234650e-02],
         [-5.78856990e-02,  5.78856133e-02],
         [ 6.62433522e-05, -6.62172679e-05],
         [-1.04983799e-01,  1.04983859e-01],
         [-4.90422821e+01,  4.90422859e+01],
         [-6.52403259e+00,  6.52403259e+00],
         [ 6.03886612e-04, -6.03879220e-04],
         [ 5.97181148e-04, -5.97203500e-04],
         [-1.26152381e-01,  1.26154214e-01],
         [-1.14098385e-01,  1.14093401e-01],
         [ 1.42772286e-03, -1.42781984e-03],
         [-1.00830004e-01,  1.00829937e-01],
         [-9.95299149e+01,  9.95299149e+01],
         [ 3.16636674e-02, -3.16635929e-02]]]], dtype=float32)

In [47]:
#bs 64, not grouped
torch.load('logs/exp2020-07-28T21:05:53.973237/40_decoder.pt')[1].softmax(-1)[:,:,-16:,:]

tensor([[[[0.7675, 0.2325],
          [0.7550, 0.2450],
          [0.1788, 0.8212],
          [0.2193, 0.7807],
          [0.7328, 0.2672],
          [0.7653, 0.2347],
          [0.6263, 0.3737],
          [0.3377, 0.6623],
          [0.7881, 0.2119],
          [0.7255, 0.2745],
          [0.1908, 0.8092],
          [0.2321, 0.7679],
          [0.7502, 0.2498],
          [0.7840, 0.2160],
          [0.3035, 0.6965],
          [0.6441, 0.3559]]]], device='cuda:0', grad_fn=<SliceBackward>)

In [48]:
np.load('logs/exp2020-07-28T21:05:53.973237/40_rel_graph_grad.npy')[0][:,:,-16:,:]

array([[[[-0.22908202,  0.22908206],
         [-0.25478688,  0.25478688],
         [ 1.8800814 , -1.880081  ],
         [-0.8104233 ,  0.8104234 ],
         [-0.29506254,  0.29506254],
         [-0.15105711,  0.15105699],
         [-0.9499444 ,  0.94994426],
         [-0.8086181 ,  0.8086182 ],
         [-0.19267023,  0.19267015],
         [-0.31313562,  0.31313553],
         [-0.62409824,  0.62409854],
         [-0.9084537 ,  0.9084526 ],
         [-0.27424628,  0.2742463 ],
         [-0.19576131,  0.19576131],
         [-0.83033067,  0.8303305 ],
         [-0.8858429 ,  0.8858428 ]]]], dtype=float32)

In [5]:
from models.modules_causal_vel import *
from data.AL_sampler import RandomPytorchSampler
from data.datasets import *
from data.dataset_utils import *
import argparse
from torch.utils.data import DataLoader
from utils.functions import *

parser = argparse.ArgumentParser()
parser.add_argument("-f",help="Input image, directory, or npy.")
args = parser.parse_args()
args.dims = 9
args.edge_types = 2
args.decoder_hidden = 256
args.skip_first = True
args.num_atoms = 8
args.decoder_dropout = 0.0
args.self_loop = True
args.suffix = "causal_vel_delta_grouped_46656"  
args.input_atoms = 6
args.variations = 4
args.train_size = None
args.temp = 0.01
args.hard = True
args.prediction_steps = 19
args.control_constraint = 1.0
args.gt_A=True

        
decoder = MLPDecoder_Causal(args).cuda()

train_data = load_one_graph_data(
        'test_'+args.suffix, size=args.train_size, self_loop=args.self_loop, control=True, control_nodes=args.input_atoms, variations=args.variations)
train_sampler = RandomPytorchSampler(train_data)
# batch_size fixed to be args.variations for grouped dataset
train_data_loader = DataLoader(
    train_data, batch_size=args.variations, shuffle=False, sampler=train_sampler)

off_diag = np.ones([args.num_atoms, args.num_atoms])
rel_rec = np.array(encode_onehot(np.where(off_diag)[0]), dtype=np.float32)
rel_send = np.array(encode_onehot(np.where(off_diag)[1]), dtype=np.float32)
rel_rec = torch.FloatTensor(rel_rec).cuda()
rel_send = torch.FloatTensor(rel_send).cuda()


Using learned interaction net decoder.


In [6]:
def load_predict(weight_path):
    decoder.load_state_dict(torch.load(weight_path)[0])
    decoder.rel_graph = torch.load(weight_path)[1].cuda()
    loss=[]
    for batch_idx, all_data in enumerate(train_data_loader):
        if batch_idx<20:
            data, which_node, edge = all_data[0].cuda(), all_data[1].cuda(), all_data[2].cuda()
            output, logits, msg_hook = decoder(data, rel_rec, rel_send,
                                               args.temp, args.hard, args.prediction_steps, [])
            target = data[:, :, 1:, :] 
            print('Velocity',batch_idx, output[0,-2,:,0], '\n',target[0,-2,:,0])
            print('Position',batch_idx, output[0,-1,:,0], '\n',target[0,-1,:,0])
            loss_nll = nll_gaussian(output, target, 5e-5)
            print('Nll', loss_nll)
            loss.append(loss_nll.item())
        else:
            print('Avg nll loss', np.mean(loss))
            break

In [7]:
load_predict('logs/exp2020-08-10T19:16:41.894627_train-bs_144_control-constraint_1.0_grouped_suffix_causal_vel_grouped_46656/best_decoder.pt')

Velocity 0 tensor([0.0476, 0.0601, 0.0725, 0.0850, 0.0975, 0.1100, 0.1225, 0.1351, 0.1477,
        0.1603, 0.1729, 0.1857, 0.1984, 0.2113, 0.2242, 0.2371, 0.2502, 0.2635],
       device='cuda:0', grad_fn=<SelectBackward>) 
 tensor([0.0701, 0.1049, 0.1397, 0.1745, 0.2093, 0.2441, 0.2789, 0.3137, 0.3484,
        0.3832, 0.4180, 0.4528, 0.4876, 0.5224, 0.5572, 0.5920, 0.6268, 0.6616],
       device='cuda:0')
Position 0 tensor([0.0030, 0.0141, 0.0252, 0.0365, 0.0478, 0.0593, 0.0708, 0.0825, 0.0942,
        0.1062, 0.1182, 0.1305, 0.1428, 0.1554, 0.1681, 0.1809, 0.1940, 0.2073],
       device='cuda:0', grad_fn=<SelectBackward>) 
 tensor([0.0701, 0.1049, 0.1397, 0.1745, 0.2093, 0.2441, 0.2789, 0.3137, 0.3484,
        0.3832, 0.4180, 0.4528, 0.4876, 0.5224, 0.5572, 0.5920, 0.6268, 0.6616],
       device='cuda:0')
Nll tensor(3234.6284, device='cuda:0', grad_fn=<DivBackward0>)
Velocity 1 tensor([ 0.0057,  0.0047,  0.0036,  0.0026,  0.0016,  0.0006, -0.0004, -0.0013,
        -0.0021, -0.0028, -0

Position 12 tensor([-0.0023,  0.0034,  0.0091,  0.0148,  0.0205,  0.0264,  0.0322,  0.0382,
         0.0442,  0.0503,  0.0565,  0.0628,  0.0692,  0.0757,  0.0823,  0.0889,
         0.0957,  0.1026], device='cuda:0', grad_fn=<SelectBackward>) 
 tensor([0.0311, 0.0555, 0.0798, 0.1042, 0.1285, 0.1529, 0.1772, 0.2016, 0.2259,
        0.2503, 0.2746, 0.2990, 0.3233, 0.3477, 0.3720, 0.3964, 0.4207, 0.4451],
       device='cuda:0')
Nll tensor(1448.6405, device='cuda:0', grad_fn=<DivBackward0>)
Velocity 13 tensor([0.0438, 0.0524, 0.0611, 0.0699, 0.0788, 0.0878, 0.0969, 0.1061, 0.1154,
        0.1248, 0.1343, 0.1438, 0.1535, 0.1633, 0.1731, 0.1830, 0.1930, 0.2031],
       device='cuda:0', grad_fn=<SelectBackward>) 
 tensor([0.0620, 0.0888, 0.1156, 0.1423, 0.1691, 0.1958, 0.2226, 0.2494, 0.2761,
        0.3029, 0.3297, 0.3564, 0.3832, 0.4099, 0.4367, 0.4635, 0.4902, 0.5170],
       device='cuda:0')
Position 13 tensor([-0.0120, -0.0161, -0.0202, -0.0244, -0.0287, -0.0329, -0.0372, -0.0414,
      

In [35]:
torch.load('logs/exp2020-08-04T14:12:38.486860_train-bs_72_grouped_control-constraint_1.0/best_decoder.pt')[1].softmax(-1)[:,:,-16:,:]

tensor([[[[0.7952, 0.2048],
          [0.7801, 0.2199],
          [0.1689, 0.8311],
          [0.1219, 0.8781],
          [0.7842, 0.2158],
          [0.7483, 0.2517],
          [0.6354, 0.3646],
          [0.3069, 0.6931],
          [0.8100, 0.1900],
          [0.7437, 0.2563],
          [0.1744, 0.8256],
          [0.1232, 0.8768],
          [0.7730, 0.2270],
          [0.5963, 0.4037],
          [0.2790, 0.7210],
          [0.6781, 0.3219]]]], device='cuda:0', grad_fn=<SliceBackward>)

In [21]:
load_predict('logs/exp2020-08-05T01:41:05.328359_train-bs_144/70_decoder.pt')

Velocity 0 tensor([[0.0758, 0.1501, 0.2288, 0.3109, 0.3962, 0.4849, 0.5763, 0.6697, 0.7642,
         0.8591, 0.9537, 1.0477, 1.1410, 1.2340, 1.3261, 1.4170, 1.5062, 1.5937],
        [0.0585, 0.1302, 0.2070, 0.2881, 0.3730, 0.4622, 0.5552, 0.6511, 0.7484,
         0.8461, 0.9436, 1.0403, 1.1358, 1.2302, 1.3234, 1.4151, 1.5050, 1.5933]],
       device='cuda:0', grad_fn=<SelectBackward>) 
 tensor([[0.0604, 0.1139, 0.1675, 0.2211, 0.2747, 0.3283, 0.3819, 0.4355, 0.4891,
         0.5427, 0.5963, 0.6499, 0.7035, 0.7571, 0.8107, 0.8643, 0.9179, 0.9715],
        [0.0604, 0.1139, 0.1675, 0.2211, 0.2747, 0.3283, 0.3819, 0.4355, 0.4891,
         0.5427, 0.5963, 0.6499, 0.7035, 0.7571, 0.8107, 0.8643, 0.9179, 0.9715]],
       device='cuda:0')
Position 0 tensor([[0.0585, 0.1302, 0.2070, 0.2881, 0.3730, 0.4622, 0.5552, 0.6511, 0.7484,
         0.8461, 0.9436, 1.0403, 1.1358, 1.2302, 1.3234, 1.4151, 1.5050, 1.5933]],
       device='cuda:0', grad_fn=<SelectBackward>) 
 tensor([[0.0604, 0.1139, 0.1675,

       device='cuda:0', grad_fn=<SelectBackward>) 
 tensor([[-0.0041, -0.0059, -0.0078, -0.0097, -0.0116, -0.0134, -0.0153, -0.0172,
         -0.0190, -0.0209, -0.0228, -0.0246, -0.0265, -0.0284, -0.0303, -0.0321,
         -0.0340, -0.0359]], device='cuda:0')
Nll tensor(5308.6050, device='cuda:0', grad_fn=<DivBackward0>)
Velocity 9 tensor([[0.0553, 0.0968, 0.1385, 0.1803, 0.2222, 0.2642, 0.3064, 0.3487, 0.3912,
         0.4338, 0.4765, 0.5192, 0.5619, 0.6046, 0.6473, 0.6899, 0.7325, 0.7750],
        [0.0039, 0.0175, 0.0328, 0.0500, 0.0688, 0.0891, 0.1108, 0.1339, 0.1579,
         0.1826, 0.2077, 0.2332, 0.2591, 0.2853, 0.3118, 0.3386, 0.3658, 0.3931]],
       device='cuda:0', grad_fn=<SelectBackward>) 
 tensor([[ 0.0120,  0.0101,  0.0082,  0.0064,  0.0045,  0.0026,  0.0008, -0.0011,
         -0.0030, -0.0049, -0.0067, -0.0086, -0.0105, -0.0123, -0.0142, -0.0161,
         -0.0179, -0.0198],
        [ 0.0120,  0.0101,  0.0082,  0.0064,  0.0045,  0.0026,  0.0008, -0.0011,
         -0.0030

Velocity 17 tensor([[0.0916, 0.1769, 0.2625, 0.3482, 0.4338, 0.5191, 0.6041, 0.6887, 0.7727,
         0.8559, 0.9381, 1.0196, 1.1004, 1.1802, 1.2594, 1.3378, 1.4156, 1.4928],
        [0.0739, 0.1552, 0.2358, 0.3160, 0.3957, 0.4751, 0.5540, 0.6320, 0.7092,
         0.7858, 0.8614, 0.9360, 1.0095, 1.0818, 1.1533, 1.2239, 1.2937, 1.3630]],
       device='cuda:0', grad_fn=<SelectBackward>) 
 tensor([[0.0604, 0.1139, 0.1675, 0.2211, 0.2747, 0.3283, 0.3819, 0.4355, 0.4891,
         0.5427, 0.5963, 0.6499, 0.7035, 0.7571, 0.8107, 0.8643, 0.9179, 0.9715],
        [0.0604, 0.1139, 0.1675, 0.2211, 0.2747, 0.3283, 0.3819, 0.4355, 0.4891,
         0.5427, 0.5963, 0.6499, 0.7035, 0.7571, 0.8107, 0.8643, 0.9179, 0.9715]],
       device='cuda:0')
Position 17 tensor([[0.0739, 0.1552, 0.2358, 0.3160, 0.3957, 0.4751, 0.5540, 0.6320, 0.7092,
         0.7858, 0.8614, 0.9360, 1.0095, 1.0818, 1.1533, 1.2239, 1.2937, 1.3630]],
       device='cuda:0', grad_fn=<SelectBackward>) 
 tensor([[0.0604, 0.1139, 0.167

In [27]:
torch.load('logs/exp2020-08-05T01:41:05.328359_train-bs_144/70_decoder.pt')[1].softmax(-1)[:,:,-16:,:]

tensor([[[[0.6079, 0.3921],
          [0.6377, 0.3623],
          [0.2464, 0.7536],
          [0.2154, 0.7846],
          [0.6462, 0.3538],
          [0.5749, 0.4251],
          [0.5649, 0.4351],
          [0.3774, 0.6226],
          [0.6231, 0.3769],
          [0.5863, 0.4137],
          [0.2629, 0.7371],
          [0.2220, 0.7780],
          [0.6222, 0.3778],
          [0.5873, 0.4127],
          [0.3566, 0.6434],
          [0.5963, 0.4037]]]], device='cuda:0', grad_fn=<SliceBackward>)

In [2]:
def control_loss(msg_hook, control_node, input_nodes):
    """Similar to the loss in Interpretable Intuitive Physics Model
    Assume the dataset is arranged as input vars first, target vars in the bottom

    Args:
        msg_hook (torch.Tensor): shape (time_steps, batch_size, node**2, information_dim)
        control_node (int): which node to exclude since it's the controlled changing node
        input_nodes (int): total number of nodes that need to be controlled.
    """

    mean = msg_hook.mean(dim=1, keepdim=True)
    num_nodes = int(np.sqrt(msg_hook.size(2)))
    # Var same size as msg_hook
    var = (msg_hook-mean)**2
    loss = 0
    control=0
    # Only constrain on the fixed input nodes
    for i in range(msg_hook.size(2)):
        # import pdb
        # pdb.set_trace()
        if i % num_nodes != control_node[0] and i % num_nodes < input_nodes:
            # print(i)
            loss += var[:, :, i, :].sum()
        elif i % num_nodes == control_node[0] and i % num_nodes < input_nodes:
            control += var[:, :, i, :].sum()
    return loss/msg_hook.size(1), control/msg_hook.size(1)

In [4]:
args.hard = True
def load_test(weight_path):
    decoder.load_state_dict(torch.load(weight_path)[0])
    decoder.rel_graph = torch.load(weight_path)[1].cuda()
    losses=[]
    ratio = 0
    for batch_idx, all_data in enumerate(train_data_loader):
        if batch_idx<200:
            data, which_node, edge = all_data[0].cuda(), all_data[1].cuda(), all_data[2].cuda()
            output, logits, msg_hook = decoder(data, rel_rec, rel_send,
                                               args.temp, args.hard, args.prediction_steps, [])
            control_constraint_loss, control = control_loss(
                msg_hook, which_node, args.input_atoms)
            control_constraint_loss *= args.control_constraint
            
            losses.append(control_constraint_loss.item())
            x = control.item()*5/(1+control_constraint_loss.item())
            if which_node[0] == 2 or which_node[0] == 3:
                print(which_node[0], x)
                ratio += x
            elif x!=0:
                print('wrong ', which_node[0], x)
        else:
            break
    print(ratio)   
    return msg_hook, losses
    

NameError: name 'args' is not defined

In [13]:
#bs=6, not grouped
msg, losses=load_test('logs/exp2020-07-27T18:07:50.586449/40_decoder.pt')
np.mean(losses), np.var(losses)

tensor(2, device='cuda:0') 0.17411018088773414
wrong  tensor(4, device='cuda:0') 2.8614155657955024e-14
tensor(3, device='cuda:0') 0.2919103764343449
tensor(3, device='cuda:0') 0.24787986488258665
tensor(2, device='cuda:0') 2.065390229285079
tensor(2, device='cuda:0') 0.1340693788267446
tensor(2, device='cuda:0') 0.05864399499341256
wrong  tensor(5, device='cuda:0') 1.2267527952657956e-06
wrong  tensor(4, device='cuda:0') 8.87606439373944e-13
tensor(2, device='cuda:0') 0.3422503773653377
wrong  tensor(0, device='cuda:0') 0.0001713440864484462
tensor(2, device='cuda:0') 0.16990013751213023
tensor(3, device='cuda:0') 0.34517200357563826
tensor(3, device='cuda:0') 0.2475740811840386
tensor(2, device='cuda:0') 0.14221623053095847
tensor(2, device='cuda:0') 0.21238727740811855
wrong  tensor(0, device='cuda:0') 0.0002701552513540444
tensor(3, device='cuda:0') 0.34625346232355886
tensor(3, device='cuda:0') 0.0
wrong  tensor(0, device='cuda:0') 2.269577373715935e-05
tensor(3, device='cuda:0') 

(46.868651145394914, 4171.44945568075)

In [22]:
for i in range(6):
    print(msg[0,i].sum(-1).topk(5))

torch.return_types.topk(
values=tensor([21.8925, 21.7818,  9.4584,  9.4235,  3.6682], device='cuda:0',
       grad_fn=<TopkBackward>),
indices=tensor([51, 59, 50, 58, 54], device='cuda:0'))
torch.return_types.topk(
values=tensor([19.3710, 19.2545,  9.4584,  9.4235,  3.6682], device='cuda:0',
       grad_fn=<TopkBackward>),
indices=tensor([59, 51, 50, 58, 54], device='cuda:0'))
torch.return_types.topk(
values=tensor([22.4923, 22.3685,  9.4584,  9.4235,  3.6682], device='cuda:0',
       grad_fn=<TopkBackward>),
indices=tensor([51, 59, 50, 58, 54], device='cuda:0'))
torch.return_types.topk(
values=tensor([19.6513, 19.5263,  9.4584,  9.4235,  3.6682], device='cuda:0',
       grad_fn=<TopkBackward>),
indices=tensor([59, 51, 50, 58, 54], device='cuda:0'))
torch.return_types.topk(
values=tensor([20.3963, 20.3088,  9.8499,  9.7994,  3.6682], device='cuda:0',
       grad_fn=<TopkBackward>),
indices=tensor([51, 59, 50, 58, 54], device='cuda:0'))
torch.return_types.topk(
values=tensor([20.0138, 1

In [14]:
#bs=128, not grouped

#exp2020-07-28T21:04:42.546747
msg, losses=load_test('logs/exp2020-07-28T15:39:22.646783/200_decoder.pt')
np.mean(losses), np.var(losses)

wrong  tensor(4, device='cuda:0') 0.008721471943225013
tensor(2, device='cuda:0') 0.20031618526942419
wrong  tensor(0, device='cuda:0') 1.0316922763499037e-05
wrong  tensor(4, device='cuda:0') 1.2472687458587854
wrong  tensor(4, device='cuda:0') 0.00037240371435430595
wrong  tensor(4, device='cuda:0') 1.029079084234437
wrong  tensor(4, device='cuda:0') 4.502006182287298e-06
tensor(3, device='cuda:0') 0.19279953482676426
tensor(3, device='cuda:0') 0.0
wrong  tensor(0, device='cuda:0') 0.6574055184196941
tensor(2, device='cuda:0') 0.7245944364566242
tensor(2, device='cuda:0') 0.0971666275003641
wrong  tensor(1, device='cuda:0') 0.001237831930362358
tensor(2, device='cuda:0') 0.07433660453736717
wrong  tensor(5, device='cuda:0') 8.97623126836047e-06
wrong  tensor(4, device='cuda:0') 2.0028381711469333e-06
wrong  tensor(4, device='cuda:0') 1.4494439296719512
tensor(2, device='cuda:0') 0.3329028113645062
wrong  tensor(4, device='cuda:0') 5.032464374740807e-06
wrong  tensor(0, device='cuda:0

(15.58439022719569, 501.72990602268516)

In [24]:
for i in range(6):
    print(msg[0,i].sum(-1).topk(5))

torch.return_types.topk(
values=tensor([10.7449,  6.6684,  6.6093,  5.2549,  5.0360], device='cuda:0',
       grad_fn=<TopkBackward>),
indices=tensor([59, 58, 19, 10,  2], device='cuda:0'))
torch.return_types.topk(
values=tensor([11.5541,  7.3680,  6.6684,  5.2549,  5.0360], device='cuda:0',
       grad_fn=<TopkBackward>),
indices=tensor([59, 19, 58, 10,  2], device='cuda:0'))
torch.return_types.topk(
values=tensor([10.9284,  6.6684,  6.5646,  5.2549,  5.0360], device='cuda:0',
       grad_fn=<TopkBackward>),
indices=tensor([59, 58, 19, 10,  2], device='cuda:0'))
torch.return_types.topk(
values=tensor([11.6577,  7.4126,  6.6684,  5.2549,  5.0360], device='cuda:0',
       grad_fn=<TopkBackward>),
indices=tensor([59, 19, 58, 10,  2], device='cuda:0'))
torch.return_types.topk(
values=tensor([10.4796,  6.9511,  6.9081,  5.1076,  4.9646], device='cuda:0',
       grad_fn=<TopkBackward>),
indices=tensor([59, 19, 58, 10,  2], device='cuda:0'))
torch.return_types.topk(
values=tensor([10.4833,  

In [11]:
#grouped, no constraint
msg, losses=load_test('logs/exp2020-07-27T18:26:29.872853/10_decoder.pt')
np.mean(losses), np.var(losses)

tensor(2, device='cuda:0') 0.12543598473193995
wrong  tensor(4, device='cuda:0') 0.22773610302447297
tensor(3, device='cuda:0') 0.2612611463660357
tensor(3, device='cuda:0') 0.111638013489383
tensor(2, device='cuda:0') 0.5005178838233051
tensor(2, device='cuda:0') 0.08946184952022711
tensor(2, device='cuda:0') 0.03735010001723068
wrong  tensor(5, device='cuda:0') 1.0846096547099424e-07
tensor(2, device='cuda:0') 0.14699462797710633
wrong  tensor(0, device='cuda:0') 0.00035640135169846755
wrong  tensor(5, device='cuda:0') 0.10050567984580994
tensor(2, device='cuda:0') 0.06855336313174873
tensor(3, device='cuda:0') 0.16951266500781223
tensor(3, device='cuda:0') 0.08452785999685533
tensor(2, device='cuda:0') 0.07855455031887784
tensor(2, device='cuda:0') 0.08080740269711435
tensor(3, device='cuda:0') 0.20007637117741273
tensor(3, device='cuda:0') 0.12920728290041386
tensor(3, device='cuda:0') 0.06353054590772651
tensor(2, device='cuda:0') 0.10220562142104403
tensor(2, device='cuda:0') 0.0

(42.151719596685254, 3133.2525691115834)

In [32]:
#bs 64, not grouped
msg, losses=load_test('logs/exp2020-07-28T21:05:53.973237/900_decoder.pt')
np.mean(losses), np.var(losses)

tensor([4, 4, 4, 4, 4, 4], device='cuda:0') tensor(7.1171, device='cuda:0', grad_fn=<MulBackward0>)
tensor([5, 5, 5, 5, 5, 5], device='cuda:0') tensor(5.1945, device='cuda:0', grad_fn=<MulBackward0>)
tensor([3, 3, 3, 3, 3, 3], device='cuda:0') tensor(171.3818, device='cuda:0', grad_fn=<MulBackward0>)
tensor([1, 1, 1, 1, 1, 1], device='cuda:0') tensor(11.6334, device='cuda:0', grad_fn=<MulBackward0>)
tensor([3, 3, 3, 3, 3, 3], device='cuda:0') tensor(3.7213, device='cuda:0', grad_fn=<MulBackward0>)
tensor([1, 1, 1, 1, 1, 1], device='cuda:0') tensor(176.0585, device='cuda:0', grad_fn=<MulBackward0>)
tensor([0, 0, 0, 0, 0, 0], device='cuda:0') tensor(9.5150, device='cuda:0', grad_fn=<MulBackward0>)
tensor([1, 1, 1, 1, 1, 1], device='cuda:0') tensor(1154.6699, device='cuda:0', grad_fn=<MulBackward0>)
tensor([4, 4, 4, 4, 4, 4], device='cuda:0') tensor(8.9618, device='cuda:0', grad_fn=<MulBackward0>)
tensor([2, 2, 2, 2, 2, 2], device='cuda:0') tensor(792.1826, device='cuda:0', grad_fn=<MulBa

tensor([3, 3, 3, 3, 3, 3], device='cuda:0') tensor(3.9105, device='cuda:0', grad_fn=<MulBackward0>)
tensor([0, 0, 0, 0, 0, 0], device='cuda:0') tensor(10.4400, device='cuda:0', grad_fn=<MulBackward0>)
tensor([2, 2, 2, 2, 2, 2], device='cuda:0') tensor(839.3690, device='cuda:0', grad_fn=<MulBackward0>)
tensor([5, 5, 5, 5, 5, 5], device='cuda:0') tensor(11.2179, device='cuda:0', grad_fn=<MulBackward0>)
tensor([5, 5, 5, 5, 5, 5], device='cuda:0') tensor(6.5779, device='cuda:0', grad_fn=<MulBackward0>)
tensor([0, 0, 0, 0, 0, 0], device='cuda:0') tensor(6.9599, device='cuda:0', grad_fn=<MulBackward0>)
tensor([4, 4, 4, 4, 4, 4], device='cuda:0') tensor(8.3519, device='cuda:0', grad_fn=<MulBackward0>)
tensor([3, 3, 3, 3, 3, 3], device='cuda:0') tensor(316.3361, device='cuda:0', grad_fn=<MulBackward0>)
tensor([5, 5, 5, 5, 5, 5], device='cuda:0') tensor(1.5203, device='cuda:0', grad_fn=<MulBackward0>)
tensor([2, 2, 2, 2, 2, 2], device='cuda:0') tensor(436.5240, device='cuda:0', grad_fn=<MulBack

tensor([3, 3, 3, 3, 3, 3], device='cuda:0') tensor(19.1758, device='cuda:0', grad_fn=<MulBackward0>)
tensor([3, 3, 3, 3, 3, 3], device='cuda:0') tensor(166.3793, device='cuda:0', grad_fn=<MulBackward0>)
tensor([4, 4, 4, 4, 4, 4], device='cuda:0') tensor(10.6939, device='cuda:0', grad_fn=<MulBackward0>)
tensor([1, 1, 1, 1, 1, 1], device='cuda:0') tensor(622.0396, device='cuda:0', grad_fn=<MulBackward0>)
tensor([0, 0, 0, 0, 0, 0], device='cuda:0') tensor(14.2341, device='cuda:0', grad_fn=<MulBackward0>)
tensor([3, 3, 3, 3, 3, 3], device='cuda:0') tensor(164.2080, device='cuda:0', grad_fn=<MulBackward0>)
tensor([3, 3, 3, 3, 3, 3], device='cuda:0') tensor(293.2578, device='cuda:0', grad_fn=<MulBackward0>)
tensor([5, 5, 5, 5, 5, 5], device='cuda:0') tensor(3.4380, device='cuda:0', grad_fn=<MulBackward0>)
tensor([4, 4, 4, 4, 4, 4], device='cuda:0') tensor(13.0516, device='cuda:0', grad_fn=<MulBackward0>)
tensor([2, 2, 2, 2, 2, 2], device='cuda:0') tensor(819.3315, device='cuda:0', grad_fn=<M

(167.82138909563423, 58725.66606953008)

In [20]:
for i in range(6):
    print(msg[0,i].sum(-1).topk(5))


torch.return_types.topk(
values=tensor([6.7878, 6.7875, 2.9108, 2.4533, 1.8211], device='cuda:0',
       grad_fn=<TopkBackward>),
indices=tensor([58, 50, 31, 19, 26], device='cuda:0'))
torch.return_types.topk(
values=tensor([6.7878, 6.7875, 2.1945, 1.9265, 1.6866], device='cuda:0',
       grad_fn=<TopkBackward>),
indices=tensor([58, 50, 19, 31, 46], device='cuda:0'))
torch.return_types.topk(
values=tensor([6.7878, 6.7875, 3.0149, 2.5641, 1.8558], device='cuda:0',
       grad_fn=<TopkBackward>),
indices=tensor([58, 50, 31, 19, 26], device='cuda:0'))
torch.return_types.topk(
values=tensor([6.7878, 6.7875, 2.2298, 1.8914, 1.6866], device='cuda:0',
       grad_fn=<TopkBackward>),
indices=tensor([58, 50, 19, 31, 46], device='cuda:0'))
torch.return_types.topk(
values=tensor([6.7050, 6.7013, 2.6025, 2.1578, 1.6944], device='cuda:0',
       grad_fn=<TopkBackward>),
indices=tensor([50, 58, 31, 19, 26], device='cuda:0'))
torch.return_types.topk(
values=tensor([6.7050, 6.7013, 2.4086, 1.8863, 1.6

In [38]:
import torch
torch.load('logs/exp2020-08-09T02:08:37.647629_train-bs_144_grouped_control-constraint_1_suffix_causal_vel_grouped_46656/best_decoder.pt')[1].softmax(-1)[:,:,-16:,:]

tensor([[[[0.9003, 0.0997],
          [0.9011, 0.0989],
          [0.0666, 0.9334],
          [0.0953, 0.9047],
          [0.9002, 0.0998],
          [0.9022, 0.0978],
          [0.7742, 0.2258],
          [0.2208, 0.7792],
          [0.9001, 0.0999],
          [0.8999, 0.1001],
          [0.1365, 0.8635],
          [0.1860, 0.8140],
          [0.9010, 0.0990],
          [0.8978, 0.1022],
          [0.1260, 0.8740],
          [0.6534, 0.3466]]]], device='cuda:0', grad_fn=<SliceBackward>)

In [29]:
import torch
torch.load('logs/exp2020-08-11T13:51:13.638329_train-bs_144_grouped_control-constraint_1.0_suffix_causal_vel_grouped_46656/20_decoder.pt')[1].softmax(-1)[:,:,-16:,:]

tensor([[[[0.8662, 0.1338],
          [0.8729, 0.1271],
          [0.1195, 0.8805],
          [0.1711, 0.8289],
          [0.8541, 0.1459],
          [0.7976, 0.2024],
          [0.5786, 0.4214],
          [0.3002, 0.6998],
          [0.8970, 0.1030],
          [0.8823, 0.1177],
          [0.2239, 0.7761],
          [0.2775, 0.7225],
          [0.8930, 0.1070],
          [0.8565, 0.1435],
          [0.2486, 0.7514],
          [0.6040, 0.3960]]]], device='cuda:0', grad_fn=<SliceBackward>)

In [40]:
import torch
torch.load('logs/exp2020-08-09T02:10:57.211566_train-bs_144_suffix_causal_vel_grouped_46656/best_decoder.pt')[1].softmax(-1)[:,:,-16:,:]

tensor([[[[0.5897, 0.4103],
          [0.6228, 0.3772],
          [0.2497, 0.7503],
          [0.2848, 0.7152],
          [0.6196, 0.3804],
          [0.5529, 0.4471],
          [0.5428, 0.4572],
          [0.4048, 0.5952],
          [0.5791, 0.4209],
          [0.5460, 0.4540],
          [0.3240, 0.6760],
          [0.3438, 0.6562],
          [0.5852, 0.4148],
          [0.5816, 0.4184],
          [0.3598, 0.6402],
          [0.5564, 0.4436]]]], device='cuda:0', grad_fn=<SliceBackward>)

In [13]:
x = np.load('data/datasets/feat_valid_causal_vel_grouped_46656.npy')
x.shape

(4096, 8, 19, 9)

In [14]:
#cont or discrete, grouped or not, existing numbers or not
for i in range(6):
    #[shapes,colors,mus,thetas,masses,v0s]
    print(set(x[:,i,0,0]))

{10.041710932759187, 4.411697096091045, 5.732410131234542, 12.721250794583527}
{16.783817188383093, 1.608661772856792, 11.628675034729028, 12.713538781181214}
{0.30087333004661876, 0.186945816341878, 0.6657495702883091, 0.32318267696821945}
{0.8504562014538201, 0.597380938348147, 0.01587230381796445, 0.5691223732868949}
{17.488831211453824, 2.4678674136020806, 3.4073120198742424, 13.84802552808172}
{0.6577003539185905, 1.6869845231931169, 2.50164918278646, 4.9622961283978375}


In [6]:
x = np.load('data/datasets/feat_train_causal_vel_x0s.npy')
for i in range(6):
    #[shapes,colors,mus,thetas,masses,v0s]
    print(set(x[:,i,0,0]))

{1.0, 2.0, 3.0, 6.0, 9.0, 10.0}
{1.0, 3.0, 5.0, 7.0, 9.0, 11.0}
{0.3, 0.56, 0.1, 0.22, 0.28, 0.01}
{0.7853981633974483, 1.0471975511965976, 0.9817477042468103, 1.2566370614359172, 0.6283185307179586, 0.5235987755982988}
{2.0, 3.5, 5.0, 8.0, 9.0, 10.0}
{3.0, 5.0, 10.0, 11.0, 17.0, 20.0}


In [3]:
x = np.load('data/datasets/feat_valid_causal_vel_interpolation.npy')
for i in range(6):
    #[shapes,colors,mus,thetas,masses,v0s]
    print(set(x[:,i,0,0]))

{8.0, 4.0, 5.0, 7.0}
{8.0, 2.0, 4.0, 6.0}
{0.18, 0.26, 0.48, 0.5}
{0.8490790955648089, 0.6981317007977318, 0.5711986642890533, 1.1635528346628863}
{2.7, 3.6, 2.3, 7.0}
{8.0, 12.0, 5.9, 14.0}


In [5]:
x[:10,:-2,0,0]

array([[ 8.       ,  8.       ,  0.18     ,  0.8490791,  2.7      ,
         8.       ],
       [ 8.       ,  8.       ,  0.18     ,  0.8490791,  2.7      ,
        12.       ],
       [ 8.       ,  8.       ,  0.18     ,  0.8490791,  2.7      ,
         5.9      ],
       [ 8.       ,  8.       ,  0.18     ,  0.8490791,  2.7      ,
        14.       ],
       [ 8.       ,  8.       ,  0.18     ,  0.8490791,  3.6      ,
         8.       ],
       [ 8.       ,  8.       ,  0.18     ,  0.8490791,  3.6      ,
        12.       ],
       [ 8.       ,  8.       ,  0.18     ,  0.8490791,  3.6      ,
         5.9      ],
       [ 8.       ,  8.       ,  0.18     ,  0.8490791,  3.6      ,
        14.       ],
       [ 8.       ,  8.       ,  0.18     ,  0.8490791,  2.3      ,
         8.       ],
       [ 8.       ,  8.       ,  0.18     ,  0.8490791,  2.3      ,
        12.       ]])