In [1]:
import torch
import numpy as np

In [15]:
#(1, 1, 64, 2)
grads=np.load('logs/exp2020-07-19T15:48:26.908392/50_rel_graph_grad.npy')
print((np.var(grads, axis=0)/np.mean(grads, axis=0))[0,0,-16:,:])

[[  -46.488617     46.488693 ]
 [   -6.0854807     6.0854754]
 [  592.0271     -592.02747  ]
 [  985.8068     -985.8068   ]
 [   53.16188     -53.16665  ]
 [  -18.16092      18.160923 ]
 [  -26.252472     26.252474 ]
 [ 1110.2504    -1110.2504   ]
 [  -11.712641     11.7129135]
 [   35.55092     -35.552402 ]
 [ 2692.5457    -2692.5493   ]
 [ 1185.1342    -1185.134    ]
 [   -7.313931      7.313915 ]
 [  -29.893536     29.893522 ]
 [ 1071.8536    -1071.8535   ]
 [  -66.44737      66.44737  ]]


In [16]:
grads=np.load('logs/exp2020-07-18T14:48:13.747535/250_rel_graph_grad.npy')
print((np.var(grads, axis=0)/np.mean(grads, axis=0))[0,0,-16:,:])

[[-8.8132496e+00  8.8132429e+00]
 [ 1.0167863e+00 -1.0168860e+00]
 [-4.7039841e+01  4.7039864e+01]
 [ 1.0397935e+03 -1.0397936e+03]
 [ 1.1738372e+01 -1.1739287e+01]
 [-5.1682782e-01  5.1682788e-01]
 [-5.2095032e+01  5.2095066e+01]
 [-1.7477496e+03  1.7477496e+03]
 [ 1.2208236e+01 -1.2206413e+01]
 [ 3.5772496e-01 -3.5767680e-01]
 [-3.4291748e+01  3.4291740e+01]
 [ 2.1085750e+03 -2.1085735e+03]
 [-9.8978634e+00  9.8979578e+00]
 [-3.8502047e+00  3.8501971e+00]
 [-2.7408909e+03  2.7408911e+03]
 [-2.9230631e+01  2.9230581e+01]]


In [22]:
grads=np.load('logs/exp2020-07-19T16:14:11.356121/330_rel_graph_grad.npy')
print((np.var(grads, axis=0)/np.mean(grads, axis=0))[0,0,-16:,:])

[[  109.23263   -109.23269 ]
 [   84.51371    -84.51372 ]
 [   57.73035    -57.730347]
 [  229.16968   -229.1697  ]
 [   65.288734   -65.288734]
 [  102.4656    -102.4656  ]
 [-1664.2189    1664.217   ]
 [  146.43149   -146.43149 ]
 [  147.99713   -147.99701 ]
 [   97.97522    -97.97523 ]
 [   55.784103   -55.784115]
 [  245.14384   -245.14386 ]
 [   95.07129    -95.07133 ]
 [  -68.46265     68.46266 ]
 [  200.03508   -200.03506 ]
 [-2539.8542    2539.8506  ]]


In [17]:
grads=np.load('logs/exp2020-07-14T13:55:08.770691/250_rel_graph_grad.npy')
print((np.var(grads, axis=0)/np.mean(grads, axis=0))[0,0,-16:,:])

[[-2.58565105e-05 -1.48539375e-05]
 [-4.29031886e-02  2.17904244e-02]
 [-3.63917497e-05 -2.13175153e-05]
 [-6.05207402e-04  6.86264550e-03]
 [ 5.81595195e-05  8.63612586e-05]
 [-1.08603757e-07 -9.17780909e-08]
 [ 1.92072039e-05 -1.96779129e-05]
 [-2.54283285e+00  2.54268456e+00]
 [-4.00848120e-01  4.00834173e-01]
 [ 1.49848640e+00 -1.49849761e+00]
 [-1.65085745e+00  1.65084934e+00]
 [-3.55093217e+00  3.55061293e+00]
 [ 9.22753990e-01 -9.22737896e-01]
 [ 7.56168962e-01 -7.56154001e-01]
 [-3.01487744e-01  3.01488370e-01]
 [ 3.26323462e+00 -3.26335430e+00]]


In [19]:
grads=np.load('logs/exp2020-07-16T19:05:05.312565/250_rel_graph_grad.npy')
print((np.var(grads, axis=0)/np.mean(grads, axis=0))[0,0,-16:,:])

[[-0.09921756  0.09921755]
 [-1.0995629   1.0995629 ]
 [-0.07563373  0.07563376]
 [-0.27537522  0.27537522]
 [-0.12072898  0.12072899]
 [-0.0872428   0.08724279]
 [-0.12816837  0.12816834]
 [-0.20535973  0.20535971]
 [-0.03878377  0.03878377]
 [-1.0057598   1.0057598 ]
 [-0.15424001  0.15424   ]
 [-0.17178072  0.17178077]
 [-0.05697478  0.05697478]
 [-0.05754867  0.05754868]
 [-0.04651249  0.04651247]
 [-0.14415482  0.14415485]]


In [24]:
grads=np.load('logs/exp2020-07-21T21:46:59.003692/200_rel_graph_grad.npy')
print((np.var(grads, axis=0)/np.mean(grads, axis=0))[0,0,-16:,:])

[[ 1.0225382e+00 -1.0225383e+00]
 [ 1.5816960e+03 -1.5816958e+03]
 [-3.5002086e-01  3.5002089e-01]
 [-3.4555912e-01  3.4555894e-01]
 [ 2.0453544e-01 -2.0453541e-01]
 [ 2.1438594e+00 -2.1438594e+00]
 [ 4.6631036e+02 -4.6631036e+02]
 [ 6.0304352e+02 -6.0304352e+02]
 [ 1.2828732e-01 -1.2828730e-01]
 [-1.1683205e+02  1.1683223e+02]
 [-3.4345526e-01  3.4345526e-01]
 [-7.5753766e-01  7.5753754e-01]
 [-3.4006029e-01  3.4006035e-01]
 [-5.9367830e-01  5.9367830e-01]
 [ 6.0777466e+02 -6.0777386e+02]
 [-1.6225598e+03  1.6225598e+03]]


In [25]:
grads=np.load('logs/exp2020-07-21T21:46:47.864056/200_rel_graph_grad.npy')
print((np.var(grads, axis=0)/np.mean(grads, axis=0))[0,0,-16:,:])

[[-3.4328866e-01  3.4328866e-01]
 [-4.0274481e+02  4.0274603e+02]
 [-3.7801638e-01  3.7801641e-01]
 [-5.1758897e-02  5.1758897e-02]
 [-4.3250635e-01  4.3250623e-01]
 [-4.9331802e-01  4.9331802e-01]
 [-1.6924600e+03  1.6924600e+03]
 [-2.3483669e+02  2.3484052e+02]
 [-3.4155548e-01  3.4155548e-01]
 [ 3.5836432e+02 -3.5836426e+02]
 [-1.9984968e-01  1.9984968e-01]
 [-3.3631378e-01  3.3631387e-01]
 [-3.4555072e-01  3.4555072e-01]
 [ 1.2820079e+00 -1.2820076e+00]
 [ 5.4021821e+03 -5.4021792e+03]
 [ 3.0694318e+02 -3.0694318e+02]]


In [ ]:
#Current renormalization has problems
1 10 -> -1 1 -> -1  4/21 -1
1 20    1 20 -> 4/21 -1  1

-1 18/19 -1
-1 1