In [2]:
import math
import numpy as np
import itertools

In [ ]:
mus=[0.001, 0.1, 3, 0.98, 1.5,10,5,0.56,7.8]
thetas=[math.pi/90, math.pi/6,math.pi/4,math.pi/3,math.pi*44/45]
g=9.8
masses=[0.5, 1, 2, 5, 100, 7,200,134]
x0s=[0.1, 5, 10, 70, 31.5,23]
# y0s=[8, 0, 70,16,27]
v0s=[0, 27, 86, 170, 10.3,80.5,47,0.9]
shapes=[1,2,3,200,100]
colors=[40,57,213,9]
# time=np.linspace(0,36,19)
print(len(mus)*len(thetas)*len(masses)*len(v0s)*len(x0s)*len(colors)*len(shapes))

In [12]:
alls = [shapes,colors,mus,thetas,masses,v0s,x0s]
data = np.array(list(itertools.product(*alls)))
data_new = np.zeros((data.shape[0],data.shape[1]+2,data.shape[1]+3))
data_new[:,:-2,0]=data
for i in range(1,data.shape[1]+3):
    data_new[:,i-1,i]=1
data_new=np.expand_dims(data_new,2)

In [13]:
data_new=np.tile(data_new,(1,1,19,1))
interval=2
print(data_new.shape)
for i in range(1,19):
    mu = data_new[:,2,0,0]
    theta=data_new[:,3,0,0] 
    
    data_new[:,-4,i,0] = data_new[:,-4,i-1,0]+g*(np.sin(theta)-np.cos(theta)*mu)
    data_new[:,-3,i,0]= data_new[:,-4,i-1,0]*interval+0.5*g*(np.sin(theta)-np.cos(theta)*mu)*(interval**2)

data_new[:,-1,:,0] =  np.cos(data_new[:,3,:,0])  
data_new[:,-2,:,0] =  np.sin(data_new[:,3,:,0])
edge= np.zeros((9,9))

(345600, 9, 19, 10)


In [10]:
# save_ds(data_new, 'vel_delta_noshuffle')
16384/2

8192.0

In [ ]:
#test variance
step=19
u0=0
v0=0
g=9.8
mus=[0.001,0.1, 0.5, 0.98,1.5]
theta= thetas[4]
interval=2

L_vars=[]
V_vars=[]
for theta in thetas:
    L=[]
    V=[]
    for mu in mus:
        loc = np.zeros(step)
        loc[0] = u0
        vel = np.zeros(step)
        vel[0] = v0
        for i in range(1, step):
            loc[i]=loc[i-1]+vel[i-1]*interval+0.5*g*(np.sin(theta)-np.cos(theta)*mu)*(interval**2)
            vel[i] = vel[i-1]+g*(np.sin(theta)-np.cos(theta)*mu)
        V.append(vel)
        L.append(loc)
    V=np.array(V)    
    L=np.array(L)  
    V_vars.append(V.var(0))
    L_vars.append(L.var(0))

np.array(V_vars).mean(0), np.array(L_vars).mean(0)

In [5]:
# Generate toy datasets
import itertools
import numpy as np

dependents = 12
steps = 19

alls = np.random.uniform(low=0, high=10, size=(5,10))
data = np.array(list(itertools.product(*alls)))
print(data.shape)
data_new_0 = np.zeros((data.shape[0],data.shape[1]+dependents,data.shape[1]+dependents+1))
data_new_0[:,:-dependents,0]=data
for i in range(1,data.shape[1]+dependents+1):
    data_new_0[:,i-1,i]=1
data_new_0=np.expand_dims(data_new_0,2)

(100000, 5)


In [6]:
data_new=np.tile(data_new_0,(1,1,steps,1))
print(data_new.shape)
for i in range(1,steps):
    data_new[:,-10,i,0] = data_new[:,-10,i-1,0]+ data_new[:,3,i-1,0]**3/(data_new[:,0,i-1,0]**2)
    data_new[:,-11,i,0] = data_new[:,-11,i-1,0]+ np.sqrt(data_new[:,3,i-1,0]**2+data_new[:,0,i-1,0]**2)
    data_new[:,-12,i,0] = data_new[:,-12,i-1,0]+ np.sqrt(1+(data_new[:,3,i-1,0]/data_new[:,0,i-1,0])**2)
    
    data_new[:,-7,i,0] = data_new[:,-7,i-1,0]+ data_new[:,3,i-1,0]/data_new[:,4,i-1,0]
    data_new[:,-8,i,0] = data_new[:,-8,i-1,0]+ np.sin(data_new[:,3,i-1,0]/data_new[:,4,i-1,0])
    data_new[:,-9,i,0] = data_new[:,-9,i-1,0]+ np.sin(data_new[:,3,i-1,0]*data_new[:,4,i-1,0])**2
    
    data_new[:,-4,i,0] = data_new[:,-4,i-1,0]+ np.exp(data_new[:,2,i-1,0])
    data_new[:,-5,i,0] = data_new[:,-5,i-1,0]+ np.log(data_new[:,2,i-1,0])
    data_new[:,-6,i,0] = data_new[:,-6,i-1,0]+ 1/(data_new[:,1,i-1,0]**2)
    
    data_new[:,-3,i,0] = data_new[:,-3,i-1,0]+ np.sin(data_new[:,0,i-1,0])
    data_new[:,-2,i,0] = data_new[:,-2,i-1,0]+ np.cos(data_new[:,0,i-1,0])
    data_new[:,-1,i,0] = data_new[:,-1,i-1,0]+ 1/data_new[:,1,i-1,0]
    
print(data_new[208,-1,:,0])

(100000, 17, 19, 18)
[0.         0.18410143 0.36820286 0.55230428 0.73640571 0.92050714
 1.10460857 1.28870999 1.47281142 1.65691285 1.84101428 2.02511571
 2.20921713 2.39331856 2.57741999 2.76152142 2.94562285 3.12972427
 3.3138257 ]


In [10]:
#SHO 
ks=np.random.uniform(low=0, high=10, size=7)
masses=np.random.uniform(low=0, high=20, size=7)
u0s=np.random.uniform(low=-5, high=5, size=7)
v0s=np.random.uniform(low=-5, high=5, size=7)

ass=np.random.uniform(low=0, high=10, size=7)
bss = np.random.uniform(low=5, high=15, size=7)
css = np.random.uniform(low=-5, high=5, size=7)
dss = np.random.uniform(low=-3, high=8, size=7)

alls=[ks,masses,v0s,u0s,ass,bss,css,dss]

In [16]:
data_new= perm_tile(alls, ds_size, steps, interval, dependents)

data_new[:,-2,:,0] =  data_new[:,0,:,0]/data_new[:,1,:,0]
#omega
data_new[:,-1,:,0] =  np.sqrt(data_new[:,-2,:,0])
for i in range(1,steps):
    omega = data_new[:,-1,0,0]

    data_new[:,2,i,0] = -data_new[:,3,i-1,0]*omega*np.sin(omega*interval)+\
                        data_new[:,2,i-1,0]*np.cos(omega*interval)
    
    data_new[:,3,i,0]= data_new[:,3,i-1,0]*np.cos(omega*interval)+ \
                        data_new[:,2,i-1,0]*np.sin(omega*interval)/omega

save_ds(data_new, 'vel_SHO')

In [5]:
import itertools
import numpy as np
#Feymann gravity
x1s=np.random.uniform(low=0, high=10, size=5)
x2s=np.random.uniform(low=0, high=20, size=5)
y1s=np.random.uniform(low=-5, high=5, size=5)
y2s=np.random.uniform(low=-5, high=5, size=5)
z1s = np.random.uniform(low=-5, high=5, size=5)
z2s = np.random.uniform(low=-3, high=8, size=5)

m1s=np.random.uniform(low=0, high=10, size=5)
m2s = np.random.uniform(low=5, high=15, size=5)

alls=[x1s,x2s,y1s,y2s,z1s,z2s,m1s,m2s]
data_new= perm_tile(alls, 100000, 19, 2, 4)

In [8]:
data_new=np.tile(data_new,(1,1,steps,1))
for i in range(1,steps):
    m1 = data_new[:,6,0,0]
    m2 = data_new[:,7,0,0]
    
    data_new[:,0,i,0] =  data_new[:,0,i-1,0]+0.01
    data_new[:,2,i,0] =  data_new[:,2,i-1,0]*0.9

    data_new[:,-4,i,0] = (data_new[:,0,i,0]-data_new[:,1,i,0])**2
    data_new[:,-3,i,0] = (data_new[:,2,i,0]-data_new[:,3,i,0])**2
    data_new[:,-2,i,0] = (data_new[:,4,i,0]-data_new[:,5,i,0])**2
    
    data_new[:,-1,i,0]= (m1*m2)/(data_new[:,-4,i,0]+data_new[:,-3,i,0]+data_new[:,-2,i,0])

save_ds(data_new, 'vel_gravity')

(100000, 12, 12)
[37194 26553 58383 38346 85881 52183 84270 85900 12548 77917]


In [145]:
def save_ds_old(data_new, ind, shuffle=False):
    edge=np.zeros((1, data_new.shape[1],data_new.shape[1]))
#     edge=np.repeat(np.expand_dims(edge,0),data_new.shape[0],axis=0)
    print(edge.shape)
    arr=np.arange(data_new.shape[0])
    if shuffle:
        np.random.shuffle(arr)
    print(arr[:10])
    start_1 = int(data_new.shape[0]*0.75)
    start_2 = int(data_new.shape[0]*0.85)
    print(start_1, start_2-start_1, data_new.shape[0]-start_2)
    np.save('./datasets/feat_train_causal_'+str(ind)+'.npy',data_new[arr[:start_1]])
    np.save('./datasets/feat_valid_causal_'+str(ind)+'.npy',data_new[arr[:start_1]])
    np.save('./datasets/feat_test_causal_'+str(ind)+'.npy',data_new[arr[start_1:start_2]])
    np.save('./datasets/edges_train_causal_'+str(ind)+'.npy',edge[:start_1])
    np.save('./datasets/edges_valid_causal_'+str(ind)+'.npy',edge[:start_1])
    np.save('./datasets/edges_test_causal_'+str(ind)+'.npy',edge[start_1:start_2])

In [254]:
import math
import numpy as np
import itertools
np.random.seed(6)
s=4
mus=np.random.uniform(low=0,high=1,size=s)
thetas=np.random.uniform(low=0,high=1.5,size=s)#,]
g=9.8
masses=np.random.uniform(low=0,high=20,size=s)
# x0s=[8.0, 10.0, 23.0, 31.5]
# y0s=[8, 0, 70,16,27]
x0s=np.random.uniform(low=0,high=5,size=s)
shapes=np.random.uniform(low=0,high=20,size=s)
colors=np.random.uniform(low=0,high=20,size=s)
# time=np.linspace(0,36,19)
print(len(mus)*len(thetas)*len(masses)*len(x0s)*len(colors)*len(shapes))
print(x0s)

4096
[2.59018206 2.894293   3.22677548 4.95112136]


In [64]:
arr = np.arange(len(data_new)/6, dtype=int)
np.random.shuffle(arr)
valid=[]
train=[]
for i in range(len(arr)):
    if i <1000:
        valid.append(data_new[arr[i]*6:arr[i]*6+6])
    else:
        train.append(data_new[arr[i]*6:arr[i]*6+6])

In [11]:
def perm_tile(alls, ds_size, steps, interval, dependents):
    data = np.array(list(itertools.product(*alls)))
    arr=np.arange(data.shape[0])
#     np.random.shuffle(arr)
#     data=data[arr[:ds_size]]
    
    data_new_0 = np.zeros((data.shape[0],data.shape[1]+dependents,data.shape[1]+dependents+1))
    data_new_0[:,:-dependents,0]=data
    for i in range(1,data.shape[1]+dependents+1):
        data_new_0[:,i-1,i]=1
    data_new_0=np.expand_dims(data_new_0,2)   
    return data_new_0


def generate_cube_dataset(alls, steps=19, interval=1, dependents=2, g=9.8):
    data_new=perm_tile(alls, None, steps, interval, dependents)
#     data_new[:,-3,0,0] =np.sin(data_new[:,3,0,0])
#     data_new[:,-4,0,0] =np.cos(data_new[:,3,0,0])
    data_new[:,-1,0,0] =data_new[:,-3,0,0] 
    data_new=np.tile(data_new,(1,1,19,1))
    # print(data_new.shape, data_new[:,-2,i-1,0].shape)
    # print((0.5*g*(np.sin(theta)-np.cos(theta)*mu)*(interval**2))[10])
    mu = data_new[:,2,0,0]
    theta=data_new[:,3,0,0] 
    for i in range(1,19):
        data_new[:,-2,i,0] = data_new[:,-2,i-1,0]+g*(np.sin(theta)-np.cos(theta)*mu)*interval
        
#         for j in np.nonzero(data_new[:,-2,i,0]<0)[0]:
#             data_new[j ,-2, i,0]=0
            
        print(np.nonzero(data_new[:,-2,i,0]<0)[0])
        data_new[:,-1,i,0]= data_new[:,-1,i-1,0]+data_new[:,-2,i-1,0]*interval+0.5*g*(np.sin(theta)-np.cos(theta)*mu)*(interval**2)
        
#         for j in np.nonzero(data_new[:,-2,i,0]==0)[0]:
#             data_new[j ,-1, i,0]=data_new[j,-1,i-1,0]
    return data_new

def save_ds(data_new, edge, name):
    np.save('./datasets/feat_'+name+'.npy',data_new)
#     edge=np.zeros((data_new.shape[1],data_new.shape[1]))
#     edge=np.repeat(np.expand_dims(edge,0),data_new.shape[0],axis=0)
    np.save('./datasets/edges_'+name+'.npy',edge)

#8.9: delta to no delta. 8.10: added interval to vel. 8.11: change interval from 2 to 1

In [212]:
shapes=[5,7, 4, 8]
colors=[2,4,6,8]
mus=[0.18, 0.26, 0.48, 0.5]
thetas=[np.pi/3.7, np.pi/4.5, np.pi/5.5, np.pi/2.7]
masses=[2.7, 7, 3.6, 2.3]
x0s=[14, 8, 12, 5.9]
print(len(shapes)*len(colors)*len(mus)*len(thetas)*len(x0s)*len(masses))
alls = [shapes,colors,mus,thetas,masses,x0s]
data_new=generate_cube_dataset(alls, steps=19, interval=1, dependents=2)
save_ds(data_new, 'valid_causal_vel_interpolation_+200mu')


4096
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]


In [21]:
x = np.load('datasets/feat_train_causal_vel_x0s.npy')
ranges=[]
for i in range(6):
    #[shapes,colors,mus,thetas,masses,v0s]
    ranges.append(list(set(x[:,i,0,0])))
    
ratio=(0.4,0.6)
for r in ranges:
    high=np.max(r)
    low=np.min(r)
    length = high-low
    print(low-ratio[1]*length, low-ratio[0]*length, high+ratio[0]*length, high+ratio[1]*length)



-4.3999999999999995 -2.6 13.6 15.399999999999999
-5.0 -3.0 15.0 17.0
-0.32 -0.21000000000000002 0.78 0.8900000000000001
0.08377580409572777 0.23038346126325143 1.5498523757709646 1.6964600329384882
-2.8 -1.2000000000000002 13.2 14.8
-7.199999999999999 -3.8000000000000007 26.8 30.2


In [22]:
#Although the negative terms aren't realistic, we're just testing the function fitting ability,
# not the realistic physics mechanics yet.
#+- 20% of the training interval
shapes=[1,2,3,10]  
colors=[1,3,5,7]
mus=[0.8, 0.87, 0.84, 0.89]  #0.001, 0, 0.6,0.65     #
thetas=[0.21, 0.1, 1.57, 1.53] #2, 2.3, 6.7, 6.5
masses=[13.5, 13.2, 14, 14.6] #11, 11.5, 1, 1.2
x0s=[-7, -5, 27,29] #0, 2, 22, 23
print(len(shapes)*len(colors)*len(mus)*len(thetas)*len(x0s)*len(masses))
alls = [shapes,colors,mus,thetas,masses,x0s]
data_new=generate_cube_dataset(alls, steps=19, interval=1, dependents=2)
save_ds(data_new, 'valid_causal_vel_x0s_extrapolation_40_60%')

4096
[   0    1    2 ... 4061 4062 4063]
[   0    1    2 ... 4061 4062 4063]
[   0    1    2 ... 4061 4062 4063]
[   0    1    2 ... 4061 4062 4063]
[   0    1    2 ... 4061 4062 4063]
[   0    1    2 ... 4061 4062 4063]
[   0    1    2 ... 4061 4062 4063]
[   0    1    2 ... 4061 4062 4063]
[   0    1    2 ... 4061 4062 4063]
[   0    1    2 ... 4061 4062 4063]
[   0    1    2 ... 4061 4062 4063]
[   0    1    2 ... 4061 4062 4063]
[   0    1    2 ... 4061 4062 4063]
[   0    1    2 ... 4061 4062 4063]
[   0    1    2 ... 4061 4062 4063]
[   0    1    2 ... 4061 4062 4063]
[   0    1    2 ... 4061 4062 4063]
[   0    1    2 ... 4061 4062 4063]


In [244]:
shapes=[1.0, 2.0, 3.0, 10.0]
colors=[1,3,5,9]
mus=[0.56, 0.3, 0.1, 0.28, 0.22,0.01, 0.4311111, 0.37, 0.15, 0.33, 0.4, 0.09, 0.24]
thetas=[np.pi/3, np.pi/4, np.pi/6, np.pi/2.5, np.pi/5, np.pi/3.2, np.pi/5.7, np.pi/4.7, np.pi/3.8]
masses=[10, 3.5, 5, 8,2]
x0s=[3,5, 10,20,17]
print(len(shapes)*len(colors)*len(mus)*len(thetas)*len(masses)*len(x0s))
alls = [shapes,colors,mus,thetas,masses, x0s]
data_new=generate_cube_dataset(alls, steps=19, interval=1, dependents=2)
save_ds_old(data_new, 'vel_x0s_more', shuffle=True)


[array([ 4.70917883, 10.7073239 ,  0.29457038,  2.17460184, 18.44324165,
       17.90109133]), array([13.30441365,  8.42228928,  6.44415723, 17.98794043,  6.47355783,
        9.70892326]), array([0.03236728, 0.54240966, 0.80291961, 0.0551594 , 0.38226478,
       0.21097059]), array([1.27852716, 0.17785698, 0.01892709, 0.17722707, 0.41143389,
       1.34929179]), array([ 4.56263095, 19.78184679,  1.63512246,  6.01548942, 18.42830012,
       19.74819664]), array([0.25598613, 0.51748619, 3.77955296, 1.74319052, 4.83106156,
       3.31083472])]


In [37]:
shapes=np.linspace(1, 11, 6).tolist()
colors=np.linspace(1, 11, 6).tolist()
mus= np.linspace(0.01, 0.56, 6).tolist()
thetas=[np.pi/i for i in np.linspace(2.5,6,6)]
masses=np.linspace(2, 10, 6).tolist()
x0s=np.linspace(3, 20, 6).tolist()

# shapes=[8.0, 4.0, 5.0, 7.0] 
# colors=[8.0, 2.0, 4.0, 6.0] 
# mus= [0.16, 0.06, 0.41, 0.46] 
# thetas=[np.pi/3.2, np.pi/5.65, np.pi/3.9, np.pi/4.6]
# masses=[26,28,34,36] 
# x0s=[4.0, 12.0, 8, 16.0]
# {8.0, 4.0, 5.0, 7.0}
# {8.0, 2.0, 4.0, 6.0}
# {0.18, 0.26, 0.48, 0.5}
# {0.8490790955648089, 0.6981317007977318, 0.5711986642890533, 1.1635528346628863}
# {2.7, 3.6, 2.3, 7.0}
# 3.7
# 4.5
# 5.5
# 2.7

print(len(shapes)*len(colors)*len(mus)*len(thetas)*len(masses)*len(x0s))
alls = [shapes,colors,mus,thetas,masses, x0s]

46656


In [38]:
edge=np.zeros((1,1,64,2))
for i in [50, 51,58,59,61,62]:
    edge[:,:,i,1]=1
edge[:, :, :, 0] = 1.0 - edge[:, :, :, 1]
data_new=generate_cube_dataset(alls, steps=19, interval=1, dependents=2)
save_ds(data_new, edge, 'train_causal_vel_grouped_46656_x0s_spaced')

[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]


In [9]:
x=np.load('datasets/feat_tra_causal_vel_interpolation.npy')
for i in range(x.shape[0]):
    print(x[i,:-2,0,0])

[8.        8.        0.18      0.8490791 2.7       8.       ]
[ 8.         8.         0.18       0.8490791  2.7       12.       ]
[8.        8.        0.18      0.8490791 2.7       5.9      ]
[ 8.         8.         0.18       0.8490791  2.7       14.       ]
[8.        8.        0.18      0.8490791 3.6       8.       ]
[ 8.         8.         0.18       0.8490791  3.6       12.       ]
[8.        8.        0.18      0.8490791 3.6       5.9      ]
[ 8.         8.         0.18       0.8490791  3.6       14.       ]
[8.        8.        0.18      0.8490791 2.3       8.       ]
[ 8.         8.         0.18       0.8490791  2.3       12.       ]
[8.        8.        0.18      0.8490791 2.3       5.9      ]
[ 8.         8.         0.18       0.8490791  2.3       14.       ]
[8.        8.        0.18      0.8490791 7.        8.       ]
[ 8.         8.         0.18       0.8490791  7.        12.       ]
[8.        8.        0.18      0.8490791 7.        5.9      ]
[ 8.         8.         0.18

[ 8.          6.          0.48        0.57119866  2.7        12.        ]
[8.         6.         0.48       0.57119866 2.7        5.9       ]
[ 8.          6.          0.48        0.57119866  2.7        14.        ]
[8.         6.         0.48       0.57119866 3.6        8.        ]
[ 8.          6.          0.48        0.57119866  3.6        12.        ]
[8.         6.         0.48       0.57119866 3.6        5.9       ]
[ 8.          6.          0.48        0.57119866  3.6        14.        ]
[8.         6.         0.48       0.57119866 2.3        8.        ]
[ 8.          6.          0.48        0.57119866  2.3        12.        ]
[8.         6.         0.48       0.57119866 2.3        5.9       ]
[ 8.          6.          0.48        0.57119866  2.3        14.        ]
[8.         6.         0.48       0.57119866 7.         8.        ]
[ 8.          6.          0.48        0.57119866  7.         12.        ]
[8.         6.         0.48       0.57119866 7.         5.9       ]
[ 8.  

[ 4.          6.          0.26        1.16355283  2.7        14.        ]
[4.         6.         0.26       1.16355283 3.6        8.        ]
[ 4.          6.          0.26        1.16355283  3.6        12.        ]
[4.         6.         0.26       1.16355283 3.6        5.9       ]
[ 4.          6.          0.26        1.16355283  3.6        14.        ]
[4.         6.         0.26       1.16355283 2.3        8.        ]
[ 4.          6.          0.26        1.16355283  2.3        12.        ]
[4.         6.         0.26       1.16355283 2.3        5.9       ]
[ 4.          6.          0.26        1.16355283  2.3        14.        ]
[4.         6.         0.26       1.16355283 7.         8.        ]
[ 4.          6.          0.26        1.16355283  7.         12.        ]
[4.         6.         0.26       1.16355283 7.         5.9       ]
[ 4.          6.          0.26        1.16355283  7.         14.        ]
[4.         6.         0.26       0.57119866 2.7        8.        ]
[ 4.  

[5.        6.        0.18      0.8490791 3.6       8.       ]
[ 5.         6.         0.18       0.8490791  3.6       12.       ]
[5.        6.        0.18      0.8490791 3.6       5.9      ]
[ 5.         6.         0.18       0.8490791  3.6       14.       ]
[5.        6.        0.18      0.8490791 2.3       8.       ]
[ 5.         6.         0.18       0.8490791  2.3       12.       ]
[5.        6.        0.18      0.8490791 2.3       5.9      ]
[ 5.         6.         0.18       0.8490791  2.3       14.       ]
[5.        6.        0.18      0.8490791 7.        8.       ]
[ 5.         6.         0.18       0.8490791  7.        12.       ]
[5.        6.        0.18      0.8490791 7.        5.9      ]
[ 5.         6.         0.18       0.8490791  7.        14.       ]
[5.        6.        0.18      0.6981317 2.7       8.       ]
[ 5.         6.         0.18       0.6981317  2.7       12.       ]
[5.        6.        0.18      0.6981317 2.7       5.9      ]
[ 5.         6.         0.18

[7.         4.         0.48       1.16355283 2.3        5.9       ]
[ 7.          4.          0.48        1.16355283  2.3        14.        ]
[7.         4.         0.48       1.16355283 7.         8.        ]
[ 7.          4.          0.48        1.16355283  7.         12.        ]
[7.         4.         0.48       1.16355283 7.         5.9       ]
[ 7.          4.          0.48        1.16355283  7.         14.        ]
[7.         4.         0.48       0.57119866 2.7        8.        ]
[ 7.          4.          0.48        0.57119866  2.7        12.        ]
[7.         4.         0.48       0.57119866 2.7        5.9       ]
[ 7.          4.          0.48        0.57119866  2.7        14.        ]
[7.         4.         0.48       0.57119866 3.6        8.        ]
[ 7.          4.          0.48        0.57119866  3.6        12.        ]
[7.         4.         0.48       0.57119866 3.6        5.9       ]
[ 7.          4.          0.48        0.57119866  3.6        14.        ]
[7.   

In [348]:
def analytic_zero_start(m,g,c,v_term,seconds=10, timestep=1):
    v=[]
    x=[]
    for t in np.arange(0, seconds, timestep):
        v.append(v_term*np.tanh(g*t/v_term))
        x.append((v_term**2/g)*np.log(np.cosh(g*t/v_term)))
    return v,x 

In [364]:
def numerical(m,g,c,v_term,seconds=10, interval=0.01, timestep=1):
    v=[0]
    x=[0]
    steps=int(seconds/interval)
    for t in np.arange(1, steps):
        a=g-c*(v[t-1]**2)/m
        v.append(v[t-1]+a*interval)
        x.append(x[t-1]+v[t-1]*interval)
    return v[::int(timestep/interval)], x[::int(timestep/interval)]

def numerical_a(m,g,c,v_term,seconds=10, interval=0.01, timestep=1):
    v=[0]
    x=[0]
    steps=int(seconds/interval)
    for t in np.arange(1, steps):
        a=g-c*(v[t-1]**2)/m
        v.append(v[t-1]+a*interval)
        x.append(x[t-1]+v[t-1]*interval+0.5*a*(interval**2))
    return v[::int(timestep/interval)], x[::int(timestep/interval)]


def analytic_interval(m,g,c,v_term,seconds=10, timestep=1):
    v=[0]
    x=[0]
    steps=int(seconds//timestep)
    for t in np.arange(1,steps):
        v_next=v_term*np.tanh(timestep*g/v_term+np.arctanh(v[t-1]/v_term))
        v.append(v_next)
        x_c=np.arccosh(np.exp(x[t-1]*g/(v_term**2)))
        x_next=(v_term**2/g)*np.log(np.cosh(timestep*g/v_term+x_c))
        x.append(x_next)
    return v,x


63.333333333333336

In [366]:
g=9.8
for m in [20,40,60,10]:
    for c in [0.1, 1, 0.5]:
        v_term = np.sqrt(m*g/c)
        print(m,c,v_term)
        v1,x1=analytic_zero_start(m,g,c,v_term,seconds=19)
        v2,x2=analytic_interval(m,g,c,v_term,seconds=19)
        v3,x3=numerical(m,g,c,v_term,interval=0.1,seconds=19)
        #I dont' know why but adding 1/2 a t**2 doesn't reduce the error.
        v4,x4=numerical_a(m,g,c,v_term,interval=0.1,seconds=19)
        print(v1, len(v1))
        print(v2, len(v2))
        print(v3, len(v3))
        print(v4, len(v4), '\n')
        print(x1)
        print(x2)
        print(x3)
        print(x4, '\n')

20 0.1 44.27188724235731
[0.0, 9.643009628211004, 18.41248193796317, 25.72511459024857, 31.394657364033414, 35.54710812900618, 38.463330524797016, 40.45147154028508, 41.77961461388711, 42.654849683573005, 43.22645428282862, 43.59757048929111, 43.83759876389078, 43.99245881620138, 44.09221095590314, 44.15639953468101, 44.197676278654974, 44.22420815512198, 44.24125764895736] 19
[0, 9.643009628211004, 18.41248193796317, 25.725114590248566, 31.394657364033414, 35.54710812900618, 38.463330524797016, 40.451471540285084, 41.77961461388712, 42.654849683573005, 43.22645428282862, 43.5975704892911, 43.83759876389078, 43.99245881620138, 44.09221095590314, 44.15639953468101, 44.197676278654974, 44.224208155121985, 44.241257648957365] 19
[0, 9.665069309599149, 18.48898641205141, 25.859182825386217, 31.566017216485182, 35.728577730303414, 38.63324200897028, 40.597713489064034, 41.898253850289095, 42.74709197814267, 43.29597145661887, 43.64875112746507, 43.874611204031496, 44.01885319292824, 44.1108

In [49]:
def analytic_zero_start_SHO(A, omega, seconds=10, timestep=1):
    v=[]
    x=[]
    for t in np.arange(0, seconds, timestep):
        x.append(A*np.cos(omega*t))
        v.append(-A*omega*np.sin(omega*t))
    return v,x

In [60]:
def analytic_interval_SHO(A, omega, seconds=10, timestep=1):
    v=[0]
    x=[A]
    steps=int(seconds//timestep)
    for t in np.arange(1,steps):
        x.append(x[t-1]*np.cos(omega*timestep)+(v[t-1]/omega)*np.sin(omega*timestep))
        v.append(-x[t-1]*omega*np.sin(omega*timestep)+v[t-1]*np.cos(omega*timestep))
    return v,x

In [64]:
def numerical_SHO(A, omega, seconds=10, interval=0.001, timestep=1):
    v=[0]
    x=[A]
    steps=int(seconds//interval)
    for t in np.arange(1, steps):
        x.append(x[t-1]+v[t-1]*interval)
        v.append(v[t-1]-(omega**2)*x[t-1]*interval)
    return v[::int(timestep//interval)],x[::int(timestep//interval)]

In [92]:
for A in [0.01, 5,10,100]:
    for m in [2,4,6,100]:
        for k in [0.1, 1, 10, 50]:
            omega=np.sqrt(k/m)
            print(A, m, k)
            v1,x1=analytic_zero_start_SHO(A, omega,seconds=19)
            v2,x2=analytic_interval_SHO(A, omega,seconds=19)
            v3,x3=numerical_SHO(A, omega,seconds=19)
            print(v1)
            print(v2)
            print(v3, '\n')
            print(x1)
            print(x2)
            print(x3, '\n')

0.01 2 0.1
[-0.0, -0.0004958437376078142, -0.0009669984170995774, -0.0013900042982762071, -0.0017437990665581425, -0.002010766568038895, -0.0021776139532595734, -0.002236033554949641, -0.0021831165435084645, -0.002021497763488285, -0.001759224539378495, -0.0014093559831153892, -0.000989312754603298, -0.0005200096519800818, -2.4814221704239938e-05, 0.00047161675863565186, 0.0009445649909254548, 0.0013704814303608106, 0.0017281588398058163]
[0, -0.0004958437376078142, -0.0009669984170995775, -0.0013900042982762071, -0.0017437990665581423, -0.0020107665680388948, -0.0021776139532595725, -0.00223603355494964, -0.002183116543508463, -0.002021497763488283, -0.0017592245393784935, -0.0014093559831153872, -0.0009893127546032967, -0.0005200096519800803, -2.4814221704239125e-05, 0.0004716167586356527, 0.0009445649909254546, 0.0013704814303608093, 0.0017281588398058146]
[0, -0.0004953685367754304, -0.0009661449075505379, -0.001388933060024024, -0.0017427205061668716, -0.00200992263867294, -0.0021

[-0.0, 0.013570466408978863, -0.025062031318966775, 0.03271426654738343, -0.03535490263733963, 0.03257941242224756, -0.02481298178700589, 0.0132453741341997, 0.0003513331318714153, -0.01389421859458805, 0.02530860596497047, -0.03284589012516871, 0.035351411326083125, -0.03244134106666172, 0.02456148196283209, -0.012918973873247145, -0.000702631569450764, 0.014216598720365048, -0.025552681375668712]
[0, 0.013570466408978863, -0.02506203131896677, 0.03271426654738343, -0.03535490263733963, 0.03257941242224755, -0.024812981787005882, 0.013245374134199697, 0.00035133313187141885, -0.01389421859458805, 0.025308605964970463, -0.0328458901251687, 0.035351411326083104, -0.0324413410666617, 0.02456148196283207, -0.012918973873247131, -0.0007026315694507665, 0.014216598720365039, -0.025552681375668698]
[0, 0.013538743897670286, -0.025197019466635374, 0.03318542264886617, -0.03624790695970019, 0.03385872762341335, -0.026311248191006758, 0.0146838000715944, -0.0006862210104347862, -0.0135911833979

[-0.0, -9.998333416664683e-06, -1.9986669333079377e-05, -2.9955020245661257e-05, -3.9893418634165954e-05, -4.979192692837722e-05, -5.964064744484905e-05, -6.942973228376432e-05, -7.914939317601399e-05, -8.878991127065054e-05, -9.83416468529291e-05, -0.0001077950489832188, -0.0001171406650471466, -0.00012636915020742396, -0.0001354712767479054, -0.00014443794330053566, -0.0001532601839459595, -0.00016192917717869362, -0.00017043625472789735]
[0, -9.998333416664683e-06, -1.998666933307938e-05, -2.995502024566126e-05, -3.9893418634165954e-05, -4.979192692837722e-05, -5.964064744484905e-05, -6.942973228376432e-05, -7.9149393176014e-05, -8.878991127065058e-05, -9.834164685292914e-05, -0.00010779504898321884, -0.00011714066504714665, -0.000126369150207424, -0.00013547127674790545, -0.00014443794330053575, -0.00015326018394595957, -0.00016192917717869373, -0.00017043625472789746]
[0, -9.988343397098451e-06, -1.996672921989352e-05, -2.9925199842621905e-05, -3.9853817503319155e-05, -4.974267422

[-0.0, -2.296813424663921, -3.4922799931830424, -3.0131605679215303, -1.08919809058432, 1.3570466408978863, 3.152572844028823, 3.4364063022226445, 2.072445805213998, -0.2852748499306541, -2.5062031318966773, -3.5253799304662916, -2.854098957655039, -0.8142466936865687, 1.6160456585312146, 3.271426654738343, 3.3581232194568402, 1.8345634130742223, -0.5686893738922313]
[0, -2.296813424663921, -3.4922799931830415, -3.0131605679215303, -1.0891980905843193, 1.3570466408978867, 3.152572844028822, 3.436406302222643, 2.0724458052139965, -0.28527484993065366, -2.5062031318966773, -3.52537993046629, -2.8540989576550375, -0.81424669368657, 1.6160456585312164, 3.2714266547383417, 3.358123219456838, 1.8345634130742212, -0.5686893738922296]
[0, -2.2954851481713328, -3.493241089482213, -3.019339332731203, -1.0998070933434168, 1.3471749498541112, 3.15047086745254, 3.446499818582366, 2.0927961498564738, -0.2634303121609981, -2.494726774167755, -3.532882619024179, -2.880324153213804, -0.8485941660714088

[-0.0, -7.90527132851738, 0.16351767422346752, 7.901889024650465, -0.3269653867164831, -7.8951258640496915, 0.4902732056820146, 7.884984740362007, -0.6533712591770826, -7.8714699925101925, 0.8161897650077367, 7.854587402836437, -0.9786590605856732, -7.834344194628339, 1.1407096327337323, 7.810749029028384, -1.3022721474272516, -7.783812001328257, 1.4632774794591044]
[0, -7.90527132851738, 0.16351767422346752, 7.901889024650465, -0.3269653867164831, -7.895125864049692, 0.49027320568201804, 7.884984740362007, -0.6533712591770824, -7.871469992510191, 0.816189765007733, 7.854587402836436, -0.97865906058568, -7.834344194628336, 1.1407096327337216, 7.8107490290283845, -1.3022721474272512, -7.783812001328256, 1.4632774794591146]
[0, -7.915268827762113, 0.13884777641492857, 7.9326262583183675, -0.2783472380570551, -7.947580026571481, 0.41845785006586245, 7.960113401224224, -0.559138682722241, -7.970210327120343, 0.7003484223216242, 7.977855433671037, -0.8420453822224465, -7.983034043108689, 0.

[-0.0, -3.638632359783542, 7.042233178140715, -9.990952393938628, 12.294322283594521, -13.80356041400952, 14.4211800019374, -14.107286914249967, 12.882156564604724, -10.824924256064405, 8.068473564857442, -4.790852941819514, 1.2037749621911449, 2.461058903967923, -5.966924671526497, 9.087366641225215, -11.620824937387646, 13.403654940384808, -14.320697644779143]
[0, -3.638632359783542, 7.042233178140716, -9.99095239393863, 12.294322283594521, -13.803560414009517, 14.421180001937397, -14.107286914249958, 12.88215656460472, -10.82492425606442, 8.068473564857438, -4.790852941819487, 1.2037749621911429, 2.461058903967899, -5.966924671526545, 9.087366641225234, -11.620824937387644, 13.403654940384795, -14.32069764477913]
[0, -3.694395817447121, 7.174538075301855, -10.207714586313278, 12.588925686260318, -14.15471843450087, 14.794379676418476, -14.457723185011446, 13.158925701712551, -10.976124310011459, 8.046766423673118, -4.5589854291441885, 0.7395410177053425, 3.1609043045801246, -6.88421

[-0.0, -0.49584373760781414, -0.9669984170995773, -1.390004298276207, -1.7437990665581424, -2.0107665680388953, -2.177613953259573, -2.236033554949641, -2.1831165435084645, -2.0214977634882847, -1.7592245393784949, -1.4093559831153892, -0.989312754603298, -0.5200096519800818, -0.024814221704239935, 0.47161675863565183, 0.9445649909254548, 1.3704814303608106, 1.728158839805816]
[0, -0.49584373760781414, -0.9669984170995773, -1.390004298276207, -1.7437990665581422, -2.010766568038895, -2.1776139532595726, -2.2360335549496404, -2.183116543508464, -2.0214977634882842, -1.7592245393784944, -1.4093559831153881, -0.9893127546032974, -0.5200096519800808, -0.024814221704239525, 0.47161675863565267, 0.944564990925455, 1.37048143036081, 1.7281588398058156]
[0, -0.4953685367754304, -0.966144907550537, -1.3889330600240197, -1.742720506166865, -2.0099226386729265, -2.1772567540116414, -2.236402339758016, -2.184414803116859, -2.0238720684445637, -1.762746745388191, -1.4140102064273523, -0.99498823545

[-0.0, -2.397127693021015, -4.207354924039483, -4.987474933020272, -4.546487134128409, -2.9923607205197826, -0.7056000402993361, 1.7539161384480992, 3.7840124765396412, 4.887650588325485, 4.794621373315692, 3.5277016278519597, 1.3970774909946293, -1.0755999404390777, -3.2849329935939453, -4.6899998838736945, -4.946791233116909, -3.9924355631174513, -2.060592426208783]
[0, -2.397127693021015, -4.207354924039483, -4.987474933020273, -4.5464871341284105, -2.992360720519785, -0.7056000402993376, 1.753916138448099, 3.784012476539642, 4.887650588325488, 4.794621373315696, 3.5277016278519633, 1.3970774909946322, -1.0755999404390766, -3.2849329935939466, -4.689999883873698, -4.946791233116914, -3.992435563117457, -2.0605924262087876]
[0, -2.3952323402965816, -4.2057013266527, -4.988807329879563, -4.552913463784858, -3.0042416739802333, -0.7209879638368728, 1.739035541125731, 3.77467729278144, 4.888348614429016, 4.807653355614304, 3.5520139906319117, 1.4279979253773536, -1.0455316108659993, -3.

[-0.0, -12.40787896115311, -6.853249667273392, 8.622620324360444, 11.615785637680396, -2.2068679378498794, -12.834706051728382, -4.88213133865377, 10.138156135585053, 10.481743921956005, -4.34876954739463, -12.883701867148696, -2.767291611061461, 11.35524238006542, 9.039138016610215, -6.362650995291366, -12.553424056389968, -0.5709876634146638, 12.238050169639054]
[0, -12.40787896115311, -6.853249667273392, 8.622620324360438, 11.615785637680395, -2.2068679378498794, -12.834706051728377, -4.882131338653774, 10.13815613558505, 10.481743921956003, -4.348769547394628, -12.88370186714869, -2.7672916110614776, 11.355242380065405, 9.039138016610217, -6.3626509952913555, -12.553424056389963, -0.5709876634146664, 12.238050169639045]
[0, -12.413593309940232, -6.892958512465386, 8.606791333150968, 11.683581233899561, -2.1335325370780733, -12.887747947442474, -5.019156922671885, 10.122211346389868, 10.648132075659507, -4.226436896229457, -13.01271088193063, -2.992153776412905, 11.372926768906911, 

[-0.0, -4.593626849327842, -6.984559986366085, -6.026321135843061, -2.17839618116864, 2.7140932817957726, 6.305145688057646, 6.872812604445289, 4.144891610427996, -0.5705496998613082, -5.012406263793355, -7.050759860932583, -5.708197915310078, -1.6284933873731373, 3.2320913170624292, 6.542853309476686, 6.7162464389136804, 3.6691268261484447, -1.1373787477844626]
[0, -4.593626849327842, -6.984559986366083, -6.026321135843061, -2.1783961811686385, 2.7140932817957735, 6.305145688057644, 6.872812604445286, 4.144891610427993, -0.5705496998613073, -5.012406263793355, -7.05075986093258, -5.708197915310075, -1.62849338737314, 3.232091317062433, 6.542853309476683, 6.716246438913676, 3.6691268261484424, -1.1373787477844592]
[0, -4.5909702963426655, -6.986482178964426, -6.038678665462406, -2.1996141866868335, 2.6943498997082225, 6.30094173490508, 6.892999637164732, 4.1855922997129476, -0.5268606243219962, -4.98945354833551, -7.065765238048358, -5.760648306427608, -1.6971883321428176, 3.1807661210

[-0.0, -2.4895963464188613, -4.917082342646456, -7.221897165026783, -9.346540385448284, -11.238006489727223, -12.849107257057975, -14.139649009860538, -15.077435364043035, -15.639070463105822, -15.810542657034759, -15.587574064386008, -14.975727296701391, -13.990266682697872, -12.65577745440453, -11.005552395776082, -9.080761255648822, -6.929423646491378, -4.605211053031231]
[0, -2.4895963464188613, -4.917082342646456, -7.2218971650267845, -9.346540385448286, -11.238006489727223, -12.849107257057979, -14.139649009860541, -15.077435364043042, -15.63907046310583, -15.810542657034768, -15.587574064386018, -14.975727296701404, -13.990266682697886, -12.655777454404545, -11.005552395776098, -9.080761255648838, -6.929423646491393, -4.605211053031245]
[0, -2.4871585379037895, -4.91245266787693, -7.215494650522126, -9.338939133754135, -11.229911042232231, -12.841322199253836, -14.133043896414998, -15.07290621221093, -15.637499193711427, -15.812755948138147, -15.59430312078895, -14.9875700271245

[-0.0, -16.20754645415857, -29.75114482340112, -38.404705980624875, -40.74589016961245, -36.38988941499698, -26.052676359582357, -11.433323654508492, 5.065263562698334, 20.731300387061278, 32.98984378728782, 39.82602227698375, 40.11620960912408, 33.812709237540716, 21.95159394417152, 6.482412074295576, -10.052249341161145, -24.934676073396354, -35.718722908242334]
[0, -16.20754645415857, -29.75114482340112, -38.404705980624875, -40.74589016961245, -36.389889414996986, -26.052676359582364, -11.433323654508504, 5.065263562698316, 20.73130038706126, 32.989843787287796, 39.826022276983736, 40.11620960912407, 33.812709237540716, 21.951593944171524, 6.482412074295588, -10.052249341161126, -24.934676073396332, -35.71872290824231]
[0, -16.193595354358393, -29.73325786500679, -38.397305466275625, -40.763551848446745, -36.442755395226015, -26.142647952673716, -11.552011022533174, 4.936212783167591, 20.61737506659988, 32.918778999120775, 39.821763326174484, 40.192964724725826, 33.97039836881531, 

[-0.0, -9.834164685292912, -18.693080770896568, -25.69821451411595, -30.15487072808607, -31.621085314069518, -29.951454593402783, -25.31155490880906, -18.161522511297644, -9.210422106062461, 0.6540706968938701, 10.453699675452643, 19.216641116603796, 26.0738790293479, 30.34538497343104, 31.607556098601858, 29.735223601837156, 24.914065647379317, 17.622193767262917]
[0, -9.834164685292912, -18.69308077089657, -25.698214514115957, -30.154870728086077, -31.62108531406952, -29.951454593402783, -25.31155490880906, -18.16152251129764, -9.21042210606246, 0.6540706968938714, 10.453699675452643, 19.216641116603803, 26.073879029347907, 30.34538497343105, 31.60755609860186, 29.735223601837156, 24.914065647379317, 17.62219376726292]
[0, -9.825150478404703, -18.67881084763431, -25.684568305289595, -30.14882383915084, -31.62946138926271, -29.979632643319086, -25.362321256948356, -18.2342420452672, -9.30066570456579, 0.5543624913028091, 10.355505678809568, 19.13266297250678, 26.016988430826196, 30.32

In [104]:
#training
shapes=[1,2,3,6,7,10]   #1-10
colors=[7,2,4,10,5,8]  #1-10
As=[0, 1, 5,2,6, 9]  #0-9
ms=[36,40,38,50, 42, 32] #31-50
ks=[19,12,11,20,18,15]    #11-20
spring_lens=[30,25,27,23,21, 26] #21-30

#valid
# shapes=[4,5,8,9]   
# colors=[3,6,1,9]  
# As=[3,4,7,8]  
# ms=[34,44,46,48]   
# ks=[14,16,13,17]    
# spring_lens=[22,29,28,24]    
alls=[shapes, colors, As,ms, ks,spring_lens]
edge=np.zeros((1,1,64,2))
for i in [50,51,52,54,55,58,59,60,62,63]:
    edge[:,:,i,1]=1
edge[:, :, :, 0] = 1.0 - edge[:, :, :, 1]

In [88]:
def generate_SHO_dataset(alls, steps=19, interval=1, dependents=2):
    data_new=perm_tile(alls, None, steps, interval, dependents)
    data_new[:,-1,0,0] =data_new[:,2,0,0] 
    data_new=np.tile(data_new,(1,1,19,1))
    m =data_new[:,3,0,0] 
    k = data_new[:,4,0,0] 
    omega=np.sqrt(k/m)
    print(2*np.pi/omega)
    for i in range(1,steps):
        data_new[:,-2,i,0] = -data_new[:,-1,i-1,0]*omega*np.sin(omega*interval)+data_new[:,-2,i-1,0]*np.cos(omega*interval)
        data_new[:,-1,i,0]= data_new[:,-1,i-1,0]*np.cos(omega*interval)+(data_new[:,-2,i-1,0]/omega)*np.sin(omega*interval)
    data_new[:,-1,:,0] +=data_new[:,5,:,0] 
    print(data_new.shape)
    return data_new

In [105]:
def generate_SHO_dataset_numerical(alls, steps=19, interval=0.1, dependents=2):
    data_new=perm_tile(alls, None, steps, interval, dependents)
    data_new[:,-1,0,0] =data_new[:,2,0,0] 
    data_new=np.tile(data_new,(1,1,19,1))
    m =data_new[:,3,0,0] 
    k = data_new[:,4,0,0] 
    omega=np.sqrt(k/m)
    print(2*np.pi/omega)
    for i in range(1,steps):
        data_new[:,-2,i,0] = data_new[:,-2,i-1,0]-(omega**2)*data_new[:,-1,i-1,0]*interval
        data_new[:,-1,i,0]= data_new[:,-1,i-1,0]+data_new[:,-2,i-1,0]*interval
    data_new[:,-1,:,0] +=data_new[:,5,:,0] 
    print(data_new.shape)
    return data_new

In [106]:
data_new=generate_SHO_dataset(alls, steps=19, interval=0.1, dependents=2)

[8.64876941 8.64876941 8.64876941 ... 9.17717954 9.17717954 9.17717954]
(46656, 8, 19, 9)


In [108]:
data_new[1000,-2:,:,0]

array([[ 0.        , -0.21587042, -0.43096395, -0.64450646, -0.85572946,
        -1.06387274, -1.26818724, -1.46793763, -1.66240503, -1.85088957,
        -2.0327129 , -2.20722067, -2.37378482, -2.53180591, -2.68071523,
        -2.81997687, -2.94908965, -3.06758888, -3.1750481 ],
       [27.        , 26.98920324, 26.95685182, 26.90306216, 26.82802785,
        26.73201893, 26.61538094, 26.47853364, 26.32196954, 26.14625209,
        25.95201369, 25.73995339, 25.51083437, 25.26548123, 25.00477696,
        24.72965981, 24.44111992, 24.14019571, 23.82797019]])

In [90]:
# edge=np.zeros((1,1,64,2))
# for i in [50,51,52,55,62]:
#     edge[:,:,i,1]=1
# edge[:, :, :, 0] = 1.0 - edge[:, :, :, 1]
edge=np.load('datasets/edges_valid_causal_vel_SHO_spaced_wall_interpolation.npy')

In [91]:
save_ds(data_new, edge,'train_causal_vel_SHO_spaced_wall_0.1')

In [109]:
g=9.8
#train
# rhos=np.linspace(0.1,4,6).tolist()
# shapes=np.linspace(1,10,6).tolist()
# areas=np.linspace(8,15,6).tolist()
# colors=np.linspace(2,12,6).tolist()  
# ms=np.linspace(100,120,6).tolist()    
# x0s=np.linspace(50,100,6).tolist()    

# {0.1, 1.0, 2.3, 3.3, 4.0, 0.7}
# {1.0, 2.0, 3.0, 6.0, 7.0, 9.0}
# {8.94427190999916, 9.0, 10.88888, 9.6, 12.566370614359172, 15.0}
# {2.0, 4.0, 5.0, 7.0, 10.0, 12.0}
# {100.0, 101.0, 109.0, 111.0, 118.3, 120.0}
# {100.0, 74.0, 80.0, 50.0, 90.0, 60.0}


# {0.5, 1.3, 2.9, 3.6}
# {8.0, 4.0, 5.0, 7.5}
# {11.0, 12.0, 13.0, 14.0}
# {8.0, 9.0, 3.0, 6.0}
# {105.0, 114.88888, 117.0, 103.0}
# {56.0, 67.0, 78.0, 95.0}

# #valid
rhos=[0.5, 1.3, 2.9, 3.6]
shapes=[8.0, 4.0, 5.0, 7.5]
areas=[11,14,13,12] 
colors=[8.0, 9.0, 3.0, 6.0]  
ms=[105.0, 114.88888, 117.0, 103.0]
x0s=[56.0, 67.0, 78.0, 95.0] 
alls=[rhos,shapes,areas,colors,ms,x0s]

In [110]:
import warnings
warnings.filterwarnings("error")
def generate_air_resistance_freefall_dataset(alls, steps=19, interval=1, dependents=2):
    data_new=perm_tile(alls, None, steps, interval, dependents)
    data_new=np.tile(data_new,(1,1,19,1))
    m =data_new[:,4,0,0] 
    rho = data_new[:,0,0,0] 
    area=data_new[:,2,0,0]
    c=rho*area/2 #C_d defaults to 1 since it's not measurable
    v_term=np.sqrt(m*g/c)
    for i in range(0,steps):
        data_new[:,-2,i,0]=v_term*np.tanh(g*i*interval/v_term)
        data_new[:,-1,i,0]=(v_term**2/g)*np.log(np.cosh(g*i*interval/v_term))
    data_new[:,-1,:,0]+=data_new[:,5,:,0] 
    print(data_new.shape)
    return data_new

In [93]:
def generate_air_resistance_freefall_dataset_numerical(alls, steps=19, interval=1, dependents=2, delta_t=0.01):
    data_new=perm_tile(alls, None, steps, interval, dependents)
    data_new=np.tile(data_new,(1,1,19,1))
    m =data_new[:,4,0,0] 
#     rho = data_new[:,0,0,0] 
    area=data_new[:,2,0,0]
#     c=rho*area/2 #C_d defaults to 1 since it's not measurable
    c=data_new[:,0,0,0] 
    v_term=np.sqrt(m*g/c)
    
    data_new[:,-1,0,0] = data_new[:,5,0,0]
    iterations=int(interval//delta_t)
    for i in range(1,steps):
        a=g-c*(data_new[:,-2,i-1,0]**2)/m
        data_new[:,-2,i,0]= data_new[:,-2,i-1,0]+a*delta_t
        data_new[:,-1,i,0]= data_new[:,-1,i-1,0]+data_new[:,-2,i-1,0]*delta_t #+0.5*a*(delta_t**2)
#         x=np.zeros((data_new.shape[0], iterations+1))
#         x[:,0] = data_new[:,-1,i-1,0]
#         v=np.zeros((data_new.shape[0], iterations+1))
#         v[:,0] = data_new[:,-2,i-1,0]
#         for t in np.arange(1, iterations+1):
#             a=g-c*(v[:,t-1]**2)/m
#             v[:,t]= v[:,t-1]+a*delta_t
#             x[:,t]= x[:,t-1]+v[:,t-1]*delta_t #+0.5*a*(delta_t**2)
#         data_new[:,-1,i,0] = x[:,-1]
#         data_new[:,-2,i,0] = v[:,-1]

    print(data_new.shape)
    return data_new

In [111]:
data_new=generate_air_resistance_freefall_dataset(alls, steps=19, interval=0.1, dependents=2)

(4096, 8, 19, 9)


In [43]:
edge=np.zeros((1,1,64,2))
for i in [48,50, 52,54,61,62]:
    edge[:,:,i,1]=1
edge[:, :, :, 0] = 1.0 - edge[:, :, :, 1]

In [112]:
edge=np.load('datasets/edges_train_causal_vel_airfall_numerical_onestep_c_spaced.npy')
save_ds(data_new, edge, 'valid_causal_vel_airfall_numerical_0.1_c_interpolation')

In [258]:
g=9.8
# for m in [2,4,6,10,20,15]:
#     for c in [0.1, 1, 10, 5,2,9]:
        
rhos=[2]    #[0.1, 1, 5,2.3,6.3, 0.7]
shapes=[4]   #[1,2,3,6,7,9]
areas=[1]   #[4*np.pi, 3*np.sqrt(5),9,15,6.88888, 9.6]
colors=[3]    #[7,2,4,10,5,12]
ms=[60]    #[88,99,111,101,100,120]
x0s=[0]     #[80,100,60,50,74,90]
alls=[rhos,shapes,areas,colors,ms,x0s]
data_new=generate_air_resistance_freefall_dataset_numerical(alls, steps=19, interval=0.1, dependents=2, delta_t=0.1)
print(data_new[:,-2:,:,0])

1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
1 1
(1, 8, 19, 9)
[[[ 0.          0.98        1.95839933  2.93200712  3.89767934
    4.8523595   5.79311718  6.7171835   7.62198258  8.50515822
    9.36459536 10.19843595 11.00508912 11.78323581 12.53182807
   13.25008354 13.93747568 14.5937203  15.21875918]
  [ 0.          0.          0.098       0.29383993  0.58704065
    0.97680858  1.46204453  2.04135625  2.7130746   3.47527286
    4.32578868  5.26224821  6.28209181  7.38260072  8.5609243
    9.81410711 11.13911546 12.53286303 13.99223506]]]


[0.0, 9.746990744662302, 19.184023047653255, 28.03935054684306, 36.10805785857225, 43.26541551065648, 49.46483847590621, 54.72465573279103, 59.10955797959113, 62.71185054424367, 65.63571991112825, 67.98577972487482, 69.85979957771674, 71.34483058926683, 72.51575535108351, 73.43538343208215, 74.15541526487223, 74.71780671090916, 75.15623993332738]
[0, 9.746990744662302, 19.184023047653255, 28.03935054684306, 36.10805785857225, 43.26541551065648, 49.46483847590621, 54.72465573279103, 59.10955797959113, 62.71185054424367, 65.63571991112825, 67.98577972487482, 69.85979957771674, 71.34483058926682, 72.51575535108351, 73.43538343208213, 74.15541526487222, 74.71780671090916, 75.1562399333274]
[0, 9.651326024393107, 19.003083769258623, 27.790292094161497, 35.81166457630694, 42.94285536479472, 49.13508140152193, 54.40292743877117, 58.80680812131085, 62.434976415685654, 65.38822188560621, 67.76857365494118, 69.67200360361463, 71.18443167199518, 72.38012428715388, 73.32164435744237, 74.06069287352243, 74.63937908962359, 75.09162303152787, 75.44451787825759] 
[0, 4.741727961619582, 18.915337744991376, 42.09010774368769, 73.60246820343016, 112.62682027247864, 158.2521267753637, 209.55141585778634, 265.6361390853933, 325.6926051717772, 389.00174116258944, 454.9456229327285, 523.0048195323736, 592.7502037388938, 663.8320554564639, 735.9684025384394, 808.9337950639953, 882.5491534966214, 956.6729578385476, 1031.193815826316] 
[0, 4.88671892282904, 19.390223849326297, 43.06009942347331, 75.20580595910945, 114.97154852928831, 161.4165973125222, 213.58750862313875, 270.57396801289246, 331.5456286137974, 395.77152895438456, 462.62587915251106, 531.5845306930295, 602.2159525668351, 674.1696250377969, 747.1638216381607, 820.9739682074428, 895.4221972040735, 970.3683382906326]
[0, 4.635765762100346, 17.386690306665482, 35.56688272621219, 56.76658578986845, 79.47172875664965, 102.88597251484009, 126.62519284619175, 150.51146778767563, 174.4639026356866, 198.4460253437902, 222.44145425873356, 246.4428439325949, 270.4469032092291, 294.4521579758867, 318.45794807647076, 342.46397789160665, 366.4701150463297, 390.47630026546074, 414.482507006781] 

[0.0, 4.772147324694757, 17.7766690198083, 36.24476161205307, 57.72651564828676, 80.69988609457435, 104.37143082492884, 128.36114638431476, 152.4940831166665, 176.69113100025908, 200.9168057540092, 225.15524867915406, 249.39938363080103, 273.6460555127239, 297.89385798973495, 322.14216429958265, 346.3906951305982, 370.63932601327525, 394.8880014810393]

In [417]:
for 

array([ 3.        ,  2.44451349,  0.98376412, -0.84129704, -2.35480543,
       -2.99627205, -2.52814619, -1.12378626,  0.69673908,  2.25924498,
        2.98509747,  2.6054957 ,  1.26101545, -0.55044952, -2.15806963,
       -2.96650402, -2.67636977, -1.39511063,  0.40279193])

In [267]:
x=np.load('datasets/feat_train_causal_vel_airfall_numerical.npy')

In [268]:
x[:,-2:,:,0].max()

836.3895874350001

In [10]:
import sys
sys.path.insert(0,'../')
from envs.rollout_func import rollout_sliding_cube,rollout_airfall_onestep, rollout_SHO_wall
import torch
import torch.nn as nn
import numpy as np
class AbstractSimulator(object):
    def __init__(self, func):
        """
        func: the physics equation used to simulate target vars by input vars
        """
        self.func = func

    def simulate(self, inputs):
        raise NotImplementedError()
class ControlSimulator(AbstractSimulator):
    """
    Used for AL
    """

    def __init__(self, func, trajectory_len, input_nodes, target_nodes, lows, highs):
        """
        low: list of length #input_nodes. The lowest value an input var can take, ordered as input nodes.
        high: list of length #input_nodes. The highest value an input var can take, ordered as input nodes.
        control_low: interger. the lowest value the controlled input var can take.
        """

        super().__init__(func)
        self.trajectory_len = trajectory_len
        self.input_nodes = input_nodes
        self.target_nodes = target_nodes
        self.lows = lows
        self.highs = highs

    def simulate(self, control_idx, batch_size):
        inputs = []
        for i in range(self.input_nodes):
            inputs.append(
                np.random.uniform(low=self.lows[i], high=self.highs[i]))
        inputs = np.expand_dims(inputs, (0,2, 3))
        inputs = torch.FloatTensor(inputs)
        # Input vars are constant over the trajectory, and same for all datapoints in one batch
        # Controlled var is constant over the trajectory but different for all datapoints in one batch
        inputs = inputs.repeat(batch_size, 1, self.trajectory_len, 1)

        control = torch.FloatTensor(
            batch_size, 1, 1, 1).uniform_(self.lows[control_idx], self.highs[control_idx])
        control = control.repeat(1, 1, self.trajectory_len, 1)

        inputs[:, control_idx:control_idx+1, :, :] = control
        targets = self.func(inputs, self.target_nodes, interval=1, delta=False)
        return inputs, targets

    def merge_inputs_targets_onehot(self, inputs, targets):
        data = torch.cat((inputs, targets), dim=1)
        outputs = torch.zeros(
            (data.size(0), data.size(1), data.size(2), 1+data.size(1)))
        outputs[:, :, :, 0:1] = data
        # Add one hot encoding
        for i in range(1, outputs.size(-1)):
            outputs[:, i-1, :, i] = 1
        return outputs

In [33]:
x=np.load('datasets/feat_valid_causal_vel_sliding_new_spaced_interpolation.npy')
# for i in range(6):
#     #[shapes,colors,mus,thetas,masses,v0s]
#     print(set(x[:,i,0,0]))
# sorted(list(set(x[:,0,0,0])))
x[:30,:-2,0,0]

array([[ 5.90909091,  7.36363636,  0.26      ,  1.05671753,  6.36363636,
        12.27272727],
       [ 5.90909091,  7.36363636,  0.26      ,  1.05671753,  6.36363636,
        15.36363636],
       [ 5.90909091,  7.36363636,  0.26      ,  1.05671753,  6.36363636,
        10.72727273],
       [ 5.90909091,  7.36363636,  0.26      ,  1.05671753,  6.36363636,
        18.45454545],
       [ 5.90909091,  7.36363636,  0.26      ,  1.05671753,  7.09090909,
        12.27272727],
       [ 5.90909091,  7.36363636,  0.26      ,  1.05671753,  7.09090909,
        15.36363636],
       [ 5.90909091,  7.36363636,  0.26      ,  1.05671753,  7.09090909,
        10.72727273],
       [ 5.90909091,  7.36363636,  0.26      ,  1.05671753,  7.09090909,
        18.45454545],
       [ 5.90909091,  7.36363636,  0.26      ,  1.05671753,  5.63636364,
        12.27272727],
       [ 5.90909091,  7.36363636,  0.26      ,  1.05671753,  5.63636364,
        15.36363636],
       [ 5.90909091,  7.36363636,  0.26      ,  1.

In [34]:
x=np.load('datasets/feat_valid_causal_vel_sliding_new_cont_interpolation.npy')
# for i in range(6):
#     #[shapes,colors,mus,thetas,masses,v0s]
#     print(set(x[:,i,0,0]))
# sorted(list(set(x[:,0,0,0])))
x[:30,:-2,0,0]

array([[ 2.61481787, 10.19672912,  0.24746078,  1.21379218,  2.40039562,
        15.43448926],
       [ 5.52122197, 10.19672912,  0.24746078,  1.21379218,  2.40039562,
        15.43448926],
       [ 8.29730213, 10.19672912,  0.24746078,  1.21379218,  2.40039562,
        15.43448926],
       [ 1.02652013, 10.19672912,  0.24746078,  1.21379218,  2.40039562,
        15.43448926],
       [ 8.30879598,  6.63056933,  0.08383575,  1.04287605,  2.78995056,
        14.27338352],
       [ 1.13393054,  6.63056933,  0.08383575,  1.04287605,  2.78995056,
        14.27338352],
       [ 7.77315038,  6.63056933,  0.08383575,  1.04287605,  2.78995056,
        14.27338352],
       [ 7.7395821 ,  6.63056933,  0.08383575,  1.04287605,  2.78995056,
        14.27338352],
       [ 9.29696444,  9.23670594,  0.50809626,  0.72906406,  2.8019415 ,
        14.39894704],
       [ 9.10397082,  9.23670594,  0.50809626,  0.72906406,  2.8019415 ,
        14.39894704],
       [ 2.92384653,  9.23670594,  0.50809626,  0.

In [32]:
x=np.load('datasets/feat_train_causal_vel_sliding_cont_new.npy')
# for i in range(6):
#     #[shapes,colors,mus,thetas,masses,v0s]
#     print(set(x[:,i,0,0]))
# sorted(list(set(x[:,0,0,0])))
x[4*7776:4*7776+30,:-2,0,0]

In [12]:
func = rollout_SHO_wall
i=0
low=[1,1,0,32,11, 21]
high=[10,10,9,50,20,30]
simulator = ControlSimulator(func, 19, 6, 2, low, high)

In [13]:
data=np.zeros((46656,8,19,9))
for i in range(6):
    print(i)
    for j in range(1296):
        inputs, targets = simulator.simulate(i, 6)
        out=simulator.merge_inputs_targets_onehot(inputs, targets)
        data[i*7776+j*6:i*7776+(j+1)*6,:,:,:]=out

0
1
2
3
4
5


In [7]:
save_ds(data, edge, 'train_causal_vel_SHO_spaced_wall_cont')

In [8]:
data[7776*5:7776*5+6,:,0,0]

array([[  1.44090056,   2.73855019,  14.40769482,   5.63300896,
        116.02583313,  78.15653229,   0.        ,  78.15653229],
       [  1.44090056,   2.73855019,  14.40769482,   5.63300896,
        116.02583313,  70.68819427,   0.        ,  70.68819427],
       [  1.44090056,   2.73855019,  14.40769482,   5.63300896,
        116.02583313,  92.47645569,   0.        ,  92.47645569],
       [  1.44090056,   2.73855019,  14.40769482,   5.63300896,
        116.02583313,  72.05069733,   0.        ,  72.05069733],
       [  1.44090056,   2.73855019,  14.40769482,   5.63300896,
        116.02583313,  68.34518433,   0.        ,  68.34518433],
       [  1.44090056,   2.73855019,  14.40769482,   5.63300896,
        116.02583313,  74.37204742,   0.        ,  74.37204742]])

In [23]:
46656/36

1296.0