In [2]:
import math
import numpy as np
mus=[0.001, 0.1, 3, 0.98, 1.5,10,5,0.56,7.8]
thetas=[math.pi/90, math.pi/6,math.pi/4,math.pi/3,math.pi*44/45]
g=9.8
masses=[0.5, 1, 2, 5, 100, 7,200,134]
x0s=[0.1, 5, 10, 70, 31.5,23]
# y0s=[8, 0, 70,16,27]
v0s=[0, 27, 86, 170, 10.3,80.5,47,0.9]
shapes=[1,2,3,200,100]
colors=[40,57,213,9]
# time=np.linspace(0,36,19)
print(len(mus)*len(thetas)*len(masses)*len(v0s)*len(x0s)*len(colors)*len(shapes))

345600


In [12]:
import itertools
alls = [shapes,colors,mus,thetas,masses,v0s,x0s]
data = np.array(list(itertools.product(*alls)))
data_new = np.zeros((data.shape[0],data.shape[1]+2,data.shape[1]+3))
data_new[:,:-2,0]=data
for i in range(1,data.shape[1]+3):
    data_new[:,i-1,i]=1
data_new=np.expand_dims(data_new,2)

In [13]:
data_new=np.tile(data_new,(1,1,19,1))
interval=2
print(data_new.shape)
for i in range(1,19):
    mu = data_new[:,2,0,0]
    theta=data_new[:,3,0,0] 
    
    data_new[:,-4,i,0] = data_new[:,-4,i-1,0]+g*(np.sin(theta)-np.cos(theta)*mu)
    data_new[:,-3,i,0]= data_new[:,-4,i-1,0]*interval+0.5*g*(np.sin(theta)-np.cos(theta)*mu)*(interval**2)

data_new[:,-1,:,0] =  np.cos(data_new[:,3,:,0])  
data_new[:,-2,:,0] =  np.sin(data_new[:,3,:,0])
edge= np.zeros((9,9))

(345600, 9, 19, 10)


In [10]:
# save_ds(data_new, 'vel_delta_noshuffle')
16384/2

8192.0

In [ ]:
#test variance
step=19
u0=0
v0=0
g=9.8
mus=[0.001,0.1, 0.5, 0.98,1.5]
theta= thetas[4]
interval=2

L_vars=[]
V_vars=[]
for theta in thetas:
    L=[]
    V=[]
    for mu in mus:
        loc = np.zeros(step)
        loc[0] = u0
        vel = np.zeros(step)
        vel[0] = v0
        for i in range(1, step):
            loc[i]=loc[i-1]+vel[i-1]*interval+0.5*g*(np.sin(theta)-np.cos(theta)*mu)*(interval**2)
            vel[i] = vel[i-1]+g*(np.sin(theta)-np.cos(theta)*mu)
        V.append(vel)
        L.append(loc)
    V=np.array(V)    
    L=np.array(L)  
    V_vars.append(V.var(0))
    L_vars.append(L.var(0))

np.array(V_vars).mean(0), np.array(L_vars).mean(0)

In [5]:
# Generate toy datasets
import itertools
import numpy as np

dependents = 12
steps = 19

alls = np.random.uniform(low=0, high=10, size=(5,10))
data = np.array(list(itertools.product(*alls)))
print(data.shape)
data_new_0 = np.zeros((data.shape[0],data.shape[1]+dependents,data.shape[1]+dependents+1))
data_new_0[:,:-dependents,0]=data
for i in range(1,data.shape[1]+dependents+1):
    data_new_0[:,i-1,i]=1
data_new_0=np.expand_dims(data_new_0,2)

(100000, 5)


In [6]:
data_new=np.tile(data_new_0,(1,1,steps,1))
print(data_new.shape)
for i in range(1,steps):
    data_new[:,-10,i,0] = data_new[:,-10,i-1,0]+ data_new[:,3,i-1,0]**3/(data_new[:,0,i-1,0]**2)
    data_new[:,-11,i,0] = data_new[:,-11,i-1,0]+ np.sqrt(data_new[:,3,i-1,0]**2+data_new[:,0,i-1,0]**2)
    data_new[:,-12,i,0] = data_new[:,-12,i-1,0]+ np.sqrt(1+(data_new[:,3,i-1,0]/data_new[:,0,i-1,0])**2)
    
    data_new[:,-7,i,0] = data_new[:,-7,i-1,0]+ data_new[:,3,i-1,0]/data_new[:,4,i-1,0]
    data_new[:,-8,i,0] = data_new[:,-8,i-1,0]+ np.sin(data_new[:,3,i-1,0]/data_new[:,4,i-1,0])
    data_new[:,-9,i,0] = data_new[:,-9,i-1,0]+ np.sin(data_new[:,3,i-1,0]*data_new[:,4,i-1,0])**2
    
    data_new[:,-4,i,0] = data_new[:,-4,i-1,0]+ np.exp(data_new[:,2,i-1,0])
    data_new[:,-5,i,0] = data_new[:,-5,i-1,0]+ np.log(data_new[:,2,i-1,0])
    data_new[:,-6,i,0] = data_new[:,-6,i-1,0]+ 1/(data_new[:,1,i-1,0]**2)
    
    data_new[:,-3,i,0] = data_new[:,-3,i-1,0]+ np.sin(data_new[:,0,i-1,0])
    data_new[:,-2,i,0] = data_new[:,-2,i-1,0]+ np.cos(data_new[:,0,i-1,0])
    data_new[:,-1,i,0] = data_new[:,-1,i-1,0]+ 1/data_new[:,1,i-1,0]
    
print(data_new[208,-1,:,0])

(100000, 17, 19, 18)
[0.         0.18410143 0.36820286 0.55230428 0.73640571 0.92050714
 1.10460857 1.28870999 1.47281142 1.65691285 1.84101428 2.02511571
 2.20921713 2.39331856 2.57741999 2.76152142 2.94562285 3.12972427
 3.3138257 ]


In [10]:
#SHO 
ks=np.random.uniform(low=0, high=10, size=7)
masses=np.random.uniform(low=0, high=20, size=7)
u0s=np.random.uniform(low=-5, high=5, size=7)
v0s=np.random.uniform(low=-5, high=5, size=7)

ass=np.random.uniform(low=0, high=10, size=7)
bss = np.random.uniform(low=5, high=15, size=7)
css = np.random.uniform(low=-5, high=5, size=7)
dss = np.random.uniform(low=-3, high=8, size=7)

alls=[ks,masses,v0s,u0s,ass,bss,css,dss]

In [16]:
data_new= perm_tile(alls, ds_size, steps, interval, dependents)

data_new[:,-2,:,0] =  data_new[:,0,:,0]/data_new[:,1,:,0]
#omega
data_new[:,-1,:,0] =  np.sqrt(data_new[:,-2,:,0])
for i in range(1,steps):
    omega = data_new[:,-1,0,0]

    data_new[:,2,i,0] = -data_new[:,3,i-1,0]*omega*np.sin(omega*interval)+\
                        data_new[:,2,i-1,0]*np.cos(omega*interval)
    
    data_new[:,3,i,0]= data_new[:,3,i-1,0]*np.cos(omega*interval)+ \
                        data_new[:,2,i-1,0]*np.sin(omega*interval)/omega

save_ds(data_new, 'vel_SHO')

In [5]:
import itertools
import numpy as np
#Feymann gravity
x1s=np.random.uniform(low=0, high=10, size=5)
x2s=np.random.uniform(low=0, high=20, size=5)
y1s=np.random.uniform(low=-5, high=5, size=5)
y2s=np.random.uniform(low=-5, high=5, size=5)
z1s = np.random.uniform(low=-5, high=5, size=5)
z2s = np.random.uniform(low=-3, high=8, size=5)

m1s=np.random.uniform(low=0, high=10, size=5)
m2s = np.random.uniform(low=5, high=15, size=5)

alls=[x1s,x2s,y1s,y2s,z1s,z2s,m1s,m2s]
data_new= perm_tile(alls, 100000, 19, 2, 4)

In [8]:
data_new=np.tile(data_new,(1,1,steps,1))
for i in range(1,steps):
    m1 = data_new[:,6,0,0]
    m2 = data_new[:,7,0,0]
    
    data_new[:,0,i,0] =  data_new[:,0,i-1,0]+0.01
    data_new[:,2,i,0] =  data_new[:,2,i-1,0]*0.9

    data_new[:,-4,i,0] = (data_new[:,0,i,0]-data_new[:,1,i,0])**2
    data_new[:,-3,i,0] = (data_new[:,2,i,0]-data_new[:,3,i,0])**2
    data_new[:,-2,i,0] = (data_new[:,4,i,0]-data_new[:,5,i,0])**2
    
    data_new[:,-1,i,0]= (m1*m2)/(data_new[:,-4,i,0]+data_new[:,-3,i,0]+data_new[:,-2,i,0])

save_ds(data_new, 'vel_gravity')

(100000, 12, 12)
[37194 26553 58383 38346 85881 52183 84270 85900 12548 77917]


In [145]:
def save_ds_old(data_new, ind, shuffle=False):
    edge=np.zeros((1, data_new.shape[1],data_new.shape[1]))
#     edge=np.repeat(np.expand_dims(edge,0),data_new.shape[0],axis=0)
    print(edge.shape)
    arr=np.arange(data_new.shape[0])
    if shuffle:
        np.random.shuffle(arr)
    print(arr[:10])
    start_1 = int(data_new.shape[0]*0.75)
    start_2 = int(data_new.shape[0]*0.85)
    print(start_1, start_2-start_1, data_new.shape[0]-start_2)
    np.save('./datasets/feat_train_causal_'+str(ind)+'.npy',data_new[arr[:start_1]])
    np.save('./datasets/feat_valid_causal_'+str(ind)+'.npy',data_new[arr[:start_1]])
    np.save('./datasets/feat_test_causal_'+str(ind)+'.npy',data_new[arr[start_1:start_2]])
    np.save('./datasets/edges_train_causal_'+str(ind)+'.npy',edge[:start_1])
    np.save('./datasets/edges_valid_causal_'+str(ind)+'.npy',edge[:start_1])
    np.save('./datasets/edges_test_causal_'+str(ind)+'.npy',edge[start_1:start_2])

In [254]:
import math
import numpy as np
import itertools
np.random.seed(6)
s=4
mus=np.random.uniform(low=0,high=1,size=s)
thetas=np.random.uniform(low=0,high=1.5,size=s)#,]
g=9.8
masses=np.random.uniform(low=0,high=20,size=s)
# x0s=[8.0, 10.0, 23.0, 31.5]
# y0s=[8, 0, 70,16,27]
x0s=np.random.uniform(low=0,high=5,size=s)
shapes=np.random.uniform(low=0,high=20,size=s)
colors=np.random.uniform(low=0,high=20,size=s)
# time=np.linspace(0,36,19)
print(len(mus)*len(thetas)*len(masses)*len(x0s)*len(colors)*len(shapes))
print(x0s)

4096
[2.59018206 2.894293   3.22677548 4.95112136]


In [64]:
arr = np.arange(len(data_new)/6, dtype=int)
np.random.shuffle(arr)
valid=[]
train=[]
for i in range(len(arr)):
    if i <1000:
        valid.append(data_new[arr[i]*6:arr[i]*6+6])
    else:
        train.append(data_new[arr[i]*6:arr[i]*6+6])

In [247]:
def perm_tile(alls, ds_size, steps, interval, dependents):
    data = np.array(list(itertools.product(*alls)))
    arr=np.arange(data.shape[0])
#     np.random.shuffle(arr)
#     data=data[arr[:ds_size]]
    
    data_new_0 = np.zeros((data.shape[0],data.shape[1]+dependents,data.shape[1]+dependents+1))
    data_new_0[:,:-dependents,0]=data
    for i in range(1,data.shape[1]+dependents+1):
        data_new_0[:,i-1,i]=1
    data_new_0=np.expand_dims(data_new_0,2)   
    return data_new_0


def generate_cube_dataset(alls, steps=19, interval=1, dependents=2):
    data_new=perm_tile(alls, None, steps, interval, dependents)
#     data_new[:,-3,0,0] =np.sin(data_new[:,3,0,0])
#     data_new[:,-4,0,0] =np.cos(data_new[:,3,0,0])
    data_new[:,-1,0,0] =data_new[:,-3,0,0] 
    data_new=np.tile(data_new,(1,1,19,1))
    # print(data_new.shape, data_new[:,-2,i-1,0].shape)
    # print((0.5*g*(np.sin(theta)-np.cos(theta)*mu)*(interval**2))[10])
    mu = data_new[:,2,0,0]
    theta=data_new[:,3,0,0] 
    for i in range(1,19):
        data_new[:,-2,i,0] = data_new[:,-2,i-1,0]+g*(np.sin(theta)-np.cos(theta)*mu)*interval
        
#         for j in np.nonzero(data_new[:,-2,i,0]<0)[0]:
#             data_new[j ,-2, i,0]=0
            
        print(np.nonzero(data_new[:,-2,i,0]<0)[0])
        data_new[:,-1,i,0]= data_new[:,-1,i-1,0]+data_new[:,-2,i-1,0]*interval+0.5*g*(np.sin(theta)-np.cos(theta)*mu)*(interval**2)
        
#         for j in np.nonzero(data_new[:,-2,i,0]==0)[0]:
#             data_new[j ,-1, i,0]=data_new[j,-1,i-1,0]
    return data_new

def save_ds(data_new, name):
    np.save('./datasets/feat_'+name+'.npy',data_new)
    edge=np.zeros((data_new.shape[1],data_new.shape[1]))
    edge=np.repeat(np.expand_dims(edge,0),data_new.shape[0],axis=0)
    np.save('./datasets/edges_'+name+'.npy',edge)

#8.9: delta to no delta. 8.10: added interval to vel. 8.11: change interval from 2 to 1

In [212]:
shapes=[5,7, 4, 8]
colors=[2,4,6,8]
mus=[0.18, 0.26, 0.48, 0.5]
thetas=[np.pi/3.7, np.pi/4.5, np.pi/5.5, np.pi/2.7]
masses=[2.7, 7, 3.6, 2.3]
x0s=[14, 8, 12, 5.9]
print(len(shapes)*len(colors)*len(mus)*len(thetas)*len(x0s)*len(masses))
alls = [shapes,colors,mus,thetas,masses,x0s]
data_new=generate_cube_dataset(alls, steps=19, interval=1, dependents=2)
save_ds(data_new, 'valid_causal_vel_interpolation_+200mu')


4096
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]
[]


In [255]:
#Although the negative terms aren't realistic, we're just testing the function fitting ability,
# not the realistic physics mechanics yet.
#+- 20% of the training interval
# shapes=[1,2,3,10]
# colors=[1,3,5,7]
# mus=[0.001, 0.6, 0.005, 0.65]
# thetas=[np.pi/2.2, np.pi/2,np.pi/6.1, np.pi/6.3]
# masses=[11, 1, 14, 0.5]
# x0s=[0, 2, 23, 0.5]
print(len(shapes)*len(colors)*len(mus)*len(thetas)*len(x0s)*len(masses))
alls = [shapes,colors,mus,thetas,masses,x0s]
data_new=generate_cube_dataset(alls, steps=19, interval=1, dependents=2)
save_ds(data_new, 'valid_causal_vel_grouped_46656_x0s')

4096
[   0    1    2 ... 4029 4030 4031]
[   0    1    2 ... 4029 4030 4031]
[   0    1    2 ... 4029 4030 4031]
[   0    1    2 ... 4029 4030 4031]
[   0    1    2 ... 4029 4030 4031]
[   0    1    2 ... 4029 4030 4031]
[   0    1    2 ... 4029 4030 4031]
[   0    1    2 ... 4029 4030 4031]
[   0    1    2 ... 4029 4030 4031]
[   0    1    2 ... 4029 4030 4031]
[   0    1    2 ... 4029 4030 4031]
[   0    1    2 ... 4029 4030 4031]
[   0    1    2 ... 4029 4030 4031]
[   0    1    2 ... 4029 4030 4031]
[   0    1    2 ... 4029 4030 4031]
[   0    1    2 ... 4029 4030 4031]
[   0    1    2 ... 4029 4030 4031]
[   0    1    2 ... 4029 4030 4031]


In [246]:
alls

[array([ 4.70917883, 10.7073239 ,  0.29457038,  2.17460184, 18.44324165,
        17.90109133]),
 array([13.30441365,  8.42228928,  6.44415723, 17.98794043,  6.47355783,
         9.70892326]),
 array([0.03236728, 0.54240966, 0.80291961, 0.0551594 , 0.38226478,
        0.21097059]),
 array([1.27852716, 0.17785698, 0.01892709, 0.17722707, 0.41143389,
        1.34929179]),
 array([ 4.56263095, 19.78184679,  1.63512246,  6.01548942, 18.42830012,
        19.74819664]),
 array([0.25598613, 0.51748619, 3.77955296, 1.74319052, 4.83106156,
        3.31083472])]

In [244]:
shapes=[1.0, 2.0, 3.0, 10.0]
colors=[1,3,5,9]
mus=[0.56, 0.3, 0.1, 0.28, 0.22,0.01, 0.4311111, 0.37, 0.15, 0.33, 0.4, 0.09, 0.24]
thetas=[np.pi/3, np.pi/4, np.pi/6, np.pi/2.5, np.pi/5, np.pi/3.2, np.pi/5.7, np.pi/4.7, np.pi/3.8]
masses=[10, 3.5, 5, 8,2]
x0s=[3,5, 10,20,17]
print(len(shapes)*len(colors)*len(mus)*len(thetas)*len(masses)*len(x0s))
alls = [shapes,colors,mus,thetas,masses, x0s]
data_new=generate_cube_dataset(alls, steps=19, interval=1, dependents=2)
save_ds_old(data_new, 'vel_x0s_more', shuffle=True)


[array([ 4.70917883, 10.7073239 ,  0.29457038,  2.17460184, 18.44324165,
       17.90109133]), array([13.30441365,  8.42228928,  6.44415723, 17.98794043,  6.47355783,
        9.70892326]), array([0.03236728, 0.54240966, 0.80291961, 0.0551594 , 0.38226478,
       0.21097059]), array([1.27852716, 0.17785698, 0.01892709, 0.17722707, 0.41143389,
       1.34929179]), array([ 4.56263095, 19.78184679,  1.63512246,  6.01548942, 18.42830012,
       19.74819664]), array([0.25598613, 0.51748619, 3.77955296, 1.74319052, 4.83106156,
       3.31083472])]


In [185]:
data_new[1000,:,:,0]

array([[1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
        1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
        1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
        1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
        1.00000000e+00, 1.00000000e+00, 1.00000000e+00],
       [1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
        1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
        1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
        1.00000000e+00, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
        1.00000000e+00, 1.00000000e+00, 1.00000000e+00],
       [2.20000000e-01, 2.20000000e-01, 2.20000000e-01, 2.20000000e-01,
        2.20000000e-01, 2.20000000e-01, 2.20000000e-01, 2.20000000e-01,
        2.20000000e-01, 2.20000000e-01, 2.20000000e-01, 2.20000000e-01,
        2.20000000e-01, 2.20000000e-01, 2.20000000e-01, 2.20000000e-01,
        2.20000000e-01

In [240]:
f=open('./test.txt', 'w')

In [241]:
print('sss', file=f)
f.flush()

In [242]:
print('aaa', file=f)
f.flush()